### ISSUE TITLE
Template import Failed - Incorrect item Key "temperature.cpu"

### ISSUE THREAD

**Issue by captainx720** [patricegautier/unifiZabbix#1]
Thanks for putting this together.  I tried to import the template and am getting the following error.  Could there be some items missing?

Incorrect item key "temperature.cpu" provided for trigger expression on "Unifi UDMP".

**Comment by tcatut** [comment]
I just had the same issue and removed the two temperature triggers at the very bottom.  It seems they are referencing keys that don't exist anywhere else in the file.  Other triggers and items imported just fine, so it seems OK without those two entries.

**Comment by tcatut** [comment]
Yeah, I take it back... this is totally broken.  Basically the only items I see are "calculated" and throwing errors because there's no data points to calculate from.  I see that mca-dump appears to be "working" except there's nothing attached to it to actually parse the data.  Is there maybe supposed to be a preprocessing rule in here?

**Comment by tcatut** [comment]
BUMP... You have done some good work here.  Please spend a few minutes to make it correct for others to use.

**Comment by eddriesen** [comment]
Hi, this affects me to.
Ubuntu 20.04.1
Zabbix 5.0 from repo
everything pretty much stock.

**Comment by lslamp** [comment]
I tried to import and ran into the same error. temperature.cpu
I did not try to remove the triggers from the xml file because I read that other items are also broken.
Can someone please advise.
Lawrence

**Comment by patricegautier** [comment]
This was most likely due to broken export of a template inheritance hierarchy from Zabbix.  Everything has been reworked to no longer rely on this, please try again from scratch..  Thanks for you patience.
