### ISSUE TITLE
Invalid tag zabbix_export/version: unsupported version number.

### ISSUE THREAD

**Issue by deekaysu** [patricegautier/unifiZabbix#10]
Hi,
thanks for working on the unifiZabbix xmls. 
however, when i try to import the zbx_export_templates.xml, I am getting an error Invalid tag "/zabbix_export/version":unsupported version number. 

I am using zabbix version 5.0.7.

**Comment by patricegautier** [comment]
Hi there - I exported those templates with zabbix 5.2.3.  I think that might be causing the error you are getting.

Do you have the option of updating.

**Comment by patricegautier** [comment]
I don't believe I am using anything 5.2 specific in there, so as an experiment you could try to edit the XML:

<?xml version="1.0" encoding="UTF-8"?>
<zabbix_export>
    <version>5.2</version>
...

and replace 5.2 with 5.0.  That might just work.

**Comment by deekaysu** [comment]
Hi thanks for the response. changed the xml to 5.0 and i was presented with another error 

"Invalid tag "/zabbix_export/templates/template(1)/items/item(1)/preprocessing/step(1)": unexpected tag "parameters"."

**Comment by patricegautier** [comment]
sadly that sounds to me like the 5.2 format is not compatible with 5.0..  Do you have the ability to update?

**Comment by patricegautier** [comment]
BTW I have found this site: https://bestmonitoringtools.com/upgrade-zabbix-to-the-latest-version/#Step_11_How_to_upgrade_Zabbix_50_to_52 to be a good resource..

**Comment by deekaysu** [comment]
i have basic editing capability .. XML copy editor

**Comment by patricegautier** [comment]
maybe try importing the yaml version?

**Comment by patricegautier** [comment]
closing this..
