### ISSUE TITLE
"AP is not reporting statistics" / "unsupported item(s)" problem when AP have no clients

### ISSUE THREAD

**Issue by GMichu** [patricegautier/unifiZabbix#100]
I'm using the UAP-AC-LR, UAP-nanoHD, U6-Pro access points. 
When the device does not currently have any client connected, zabbix raises one of the problems:
AP has unsupported item(s).
AP AP is not reporting statistics

I believe it's due to preprocessing rule on "mca-dump" item:
![obraz](https://user-images.githubusercontent.com/67835103/233952462-7b7357e9-c11b-4fd9-a1f1-6e05c24f5443.png)

Full error message:
`{ "at":"11:11:41", "r":"validationError: .vap_table? != null and .radio_table != null and ( .radio_table | map(select(.athstats.cu_total>0)) | length>0 ) ", "device":"10.1.1.21", "mcaDumpError":"Error" }`

I would expect that the lack of connected clients would not cause a problem. In such case, it would be nice to still collect statistics on channel interference etc

**Comment by patricegautier** [comment]
Interesting.. I don't see the same issue on APs without clients here.  Could you send the output of the mca-dump script?

**Comment by patricegautier** [comment]
Also are there any active radios on that AP?

**Comment by GMichu** [comment]
Here is output of the script:
`sudo -u zabbix ./mca-dump-short.sh -d 10.1.1.14 -P 22 -u admin -i /etc/zabbix/ssh_keys/zb_id_rsa -t AP -o 20 -b
{ "at":"10:42:07", "r":"validationError: .vap_table? != null and .radio_table != null and ( .radio_table | map(select(.athstats.cu_total>0)) | length>0 ) ", "device":"10.1.1.14", "mcaDumpError":"Error" }`

Here is the dump of "output" variable https://github.com/patricegautier/unifiZabbix/blob/master/mca-dump-short.sh#L359
`{
        "anon_id": "67071874-fbc0-403c-8059-b9156c34bb09",
        "antenna_table": [
                {
                        "default": true,
                        "id": 4,
                        "name": "Combined",
                        "ra0_gain": 3,
                        "rai0_gain": 3
                }
        ],
        "architecture": "mips",
        "ble_caps": 1,
        "board_rev": 16,
        "bootid": 0,
        "bootrom_version": "v1.1.46.77",
        "cfgversion": "71d78393f0682546",
        "connect_request_ip": "10.1.1.14",
        "connect_request_port": "59673",
        "country_code": 0,
        "countrycode_table": [],
        "default": false,
        "discovery_response": false,
        "dualboot": true,
        "ever_crash": false,
        "fingerprint_req": true,
        "fw_caps": 2818506559,
        "gateway_ip": "10.1.0.1",
        "gateway_mac": "redacted",
        "guest_kicks": 0,
        "guest_token": "DE29193FABA5D725E56E4BA09519CB69",
        "has_eth1": false,
        "has_speaker": false,
        "hash_id": "c059b9156c34bb09",
        "hostname": "redacted",
        "hw_caps": 2048,
        "if_table": [
                {
                        "full_duplex": true,
                        "ip": "0.0.0.0",
                        "mac": "redacted",
                        "name": "eth0",
                        "netmask": "0.0.0.0",
                        "num_port": 1,
                        "rx_bytes": 4178490232,
                        "rx_dropped": 11052,
                        "rx_errors": 0,
                        "rx_multicast": 0,
                        "rx_packets": 281768839,
                        "speed": 1000,
                        "tx_bytes": 1371244051,
                        "tx_dropped": 0,
                        "tx_errors": 0,
                        "tx_packets": 45511747,
                        "up": true
                }
        ],
        "inform_ip": "10.1.0.13",
        "inform_min_interval": 1,
        "inform_url": "redacted",
        "internet": true,
        "ip": "10.1.1.14",
        "isolated": false,
        "kernel_version": "4.4.153",
        "last_error_conns": [
                {
                        "error_reason": 6,
                        "last_error_str": "Not Adopted (redacted)",
                        "last_managed_e_time": 0,
                        "last_managed_s_time": 9218689,
                        "timestamp": "Thu Apr 20 05:35:34 2023"
                }
        ],
        "lldp_table": [
                redacted
        ],
        "locating": false,
        "mac": "redacted",
        "manufacturer_id": 4,
        "model": "U7NHD",
        "model_display": "UAP-nanoHD",
        "netmask": "255.255.252.0",
        "port_table": [
                {
                        "autoneg": false,
                        "enable": true,
                        "flowctrl_rx": false,
                        "flowctrl_tx": false,
                        "full_duplex": true,
                        "is_uplink": true,
                        "jumbo": false,
                        "mac_table": [redacted],
                        "media": "GE",
                        "poe_caps": 0,
                        "port_idx": 0,
                        "port_poe": false,
                        "rx_broadcast": 59949390,
                        "rx_bytes": 103147410152,
                        "rx_dropped": 0,
                        "rx_errors": 0,
                        "rx_multicast": 123564051,
                        "rx_packets": 284516682,
                        "speed": 1000,
                        "stp_pathcost": 0,
                        "stp_state": "disabled",
                        "tx_broadcast": 37938,
                        "tx_bytes": 36491627657,
                        "tx_dropped": 0,
                        "tx_errors": 0,
                        "tx_multicast": 866325,
                        "tx_packets": 51706969,
                        "up": true
                }
        ],
        "radio_table": [
                {
                        "athstats": {
                                "ast_ath_reset": 0,
                                "ast_be_xmit": 0,
                                "ast_cst": 0,
                                "ast_deadqueue_reset": 0,
                                "ast_fullqueue_stop": 0,
                                "ast_txto": 0,
                                "ce_send_fail_cnt": 0,
                                "cu_interf": 0,
                                "cu_self_rx": 0,
                                "cu_self_tx": 0,
                                "cu_total": 0,
                                "invalid_mac_addr_cnt": 0,
                                "n_rx_aggr": 0,
                                "n_rx_pkts": 0,
                                "n_tx_bawadv": 0,
                                "n_tx_bawretries": 0,
                                "n_tx_pkts": 0,
                                "n_tx_queue": 0,
                                "n_tx_retries": 0,
                                "n_tx_xretries": 0,
                                "n_txaggr_compgood": 0,
                                "n_txaggr_compretries": 0,
                                "n_txaggr_compxretry": 0,
                                "n_txaggr_prepends": 0,
                                "name": "ra0",
                                "noise_floor": 0,
                                "satisfaction": -1,
                                "satisfaction_now": -1,
                                "satisfaction_real": -1,
                                "timeout_waiting_for_vap_cnt": 0
                        },
                        "builtin_ant_gain": 0,
                        "builtin_antenna": true,
                        "ieee_modes": 10,
                        "max_txpower": 23,
                        "min_txpower": 6,
                        "name": "ra0",
                        "nss": 2,
                        "radio": "ng",
                        "radio_caps": 147476,
                        "radio_caps2": 11,
                        "scan_table": []
                },
                {
                        "athstats": {
                                "ast_ath_reset": 0,
                                "ast_be_xmit": 213133763,
                                "ast_cst": 0,
                                "ast_deadqueue_reset": 0,
                                "ast_fullqueue_stop": 0,
                                "ast_txto": 0,
                                "ce_send_fail_cnt": 0,
                                "cu_interf": 0,
                                "cu_self_rx": 0,
                                "cu_self_tx": 0,
                                "cu_total": 0,
                                "invalid_mac_addr_cnt": 0,
                                "n_rx_aggr": 797181,
                                "n_rx_pkts": 38617229,
                                "n_tx_bawadv": 0,
                                "n_tx_bawretries": 0,
                                "n_tx_pkts": 80094221,
                                "n_tx_queue": 621699,
                                "n_tx_retries": 0,
                                "n_tx_xretries": 621699,
                                "n_txaggr_compgood": 0,
                                "n_txaggr_compretries": 0,
                                "n_txaggr_compxretry": 0,
                                "n_txaggr_prepends": 0,
                                "name": "rai0",
                                "noise_floor": -92,
                                "satisfaction": -1,
                                "satisfaction_now": -1,
                                "satisfaction_real": -1,
                                "timeout_waiting_for_vap_cnt": 0
                        },
                        "builtin_ant_gain": 3,
                        "builtin_antenna": true,
                        "has_dfs": true,
                        "has_fccdfs": true,
                        "has_ht160": true,
                        "ieee_modes": 21,
                        "is_11ac": true,
                        "max_txpower": 26,
                        "min_txpower": 6,
                        "name": "rai0",
                        "nss": 4,
                        "radio": "na",
                        "radio_caps": 251805700,
                        "radio_caps2": 11,
                        "scan_table": []
                }
        ],
        "required_version": "0.0.1",
        "satisfaction": -1,
        "satisfaction_now": -1,
        "satisfaction_real": -1,
        "scan_radio_table": [],
        "selfrun_beacon": true,
        "serial": "redacted",
        "spectrum_scanning": false,
        "ssh_session_table": [],
        "state": 2,
        "stats_inform_interval": 1,
        "stream_token": "",
        "support_wifi6e": false,
        "switch_caps": {
                "feature_caps": 32,
                "max_aggregate_sessions": 0,
                "max_l3_intf": 0,
                "max_mirror_sessions": 0,
                "max_reserved_routes": 0,
                "max_static_routes": 0
        },
        "sys_error_caps": 0,
        "sys_stats": {
                "loadavg_1": "0.59",
                "loadavg_15": "0.56",
                "loadavg_5": "0.59",
                "mem_buffer": 0,
                "mem_total": 127336448,
                "mem_used": 56422400
        },
        "system-stats": {
                "cpu": "0.8",
                "mem": "44.4",
                "uptime": "10935947"
        },
        "time": 1683277432,
        "time_ms": 64,
        "tm_ready": true,
        "uplink": "eth0",
        "uptime": 10935947,
        "vap_table": [
                {
                        "anomalies_bar_chart": {
                                "high_disconnect_count": 0,
                                "high_dns_latency": 0,
                                "high_icmp_rtt": 0,
                                "high_tcp_latency": 0,
                                "high_tcp_packet_loss": 0,
                                "high_wifi_latency": 0,
                                "high_wifi_retries": 0,
                                "low_phy_rate": 0,
                                "no_dhcp_response": 0,
                                "poor_stream_eff": 0,
                                "sleepy_client": 0,
                                "sta_arp_timeout": 0,
                                "sta_dns_timeout": 0,
                                "sta_ip_timeout": 0,
                                "weak_signal": 0
                        },
                        "anomalies_bar_chart_now": {
                                "high_disconnect_count": 0,
                                "high_dns_latency": 0,
                                "high_icmp_rtt": 0,
                                "high_tcp_latency": 0,
                                "high_tcp_packet_loss": 0,
                                "high_wifi_latency": 0,
                                "high_wifi_retries": 0,
                                "low_phy_rate": 0,
                                "no_dhcp_response": 0,
                                "poor_stream_eff": 0,
                                "sleepy_client": 0,
                                "sta_arp_timeout": 0,
                                "sta_dns_timeout": 0,
                                "sta_ip_timeout": 0,
                                "weak_signal": 0
                        },
                        "avg_client_signal": 0,
                        "bssid": "redacted",
                        "bw": 40,
                        "ccq": 0,
                        "channel": 40,
                        "dns_avg_latency": -1,
                        "essid": "redacted",
                        "extchannel": -1,
                        "icmp_avg_rtt": -1,
                        "id": "559d44f071b08cb47ddcf265",
                        "mac_filter_rejections": 0,
                        "name": "rai1",
                        "num_satisfaction_sta": 0,
                        "num_sta": 0,
                        "radio": "na",
                        "radio_name": "rai0",
                        "reasons_bar_chart": {
                                "no_dhcp_response": 0,
                                "phy_rate": 0,
                                "signal": 0,
                                "sleepy_client": 0,
                                "sta_arp_timeout": 0,
                                "sta_disconnects": 0,
                                "sta_dns_latency": 0,
                                "sta_dns_timeout": 0,
                                "sta_icmp_rtt": 0,
                                "sta_ip_timeout": 0,
                                "stream_eff": 0,
                                "tcp_latency": 0,
                                "tcp_packet_loss": 0,
                                "wifi_latency": 0,
                                "wifi_retries": 0
                        },
                        "reasons_bar_chart_now": {
                                "no_dhcp_response": 0,
                                "phy_rate": 0,
                                "signal": 0,
                                "sleepy_client": 0,
                                "sta_arp_timeout": 0,
                                "sta_disconnects": 0,
                                "sta_dns_latency": 0,
                                "sta_dns_timeout": 0,
                                "sta_icmp_rtt": 0,
                                "sta_ip_timeout": 0,
                                "stream_eff": 0,
                                "tcp_latency": 0,
                                "tcp_packet_loss": 0,
                                "wifi_latency": 0,
                                "wifi_retries": 0
                        },
                        "rx_bytes": 2731757856,
                        "rx_crypts": 0,
                        "rx_dropped": 0,
                        "rx_errors": 0,
                        "rx_frags": 0,
                        "rx_nwids": 0,
                        "rx_packets": 33851633,
                        "rx_tcp_stats": {
                                "goodbytes": 0,
                                "lat_avg": 0,
                                "lat_max": -1,
                                "lat_min": -1,
                                "lat_samples": 0,
                                "lat_sum": 0,
                                "retries": 0,
                                "stalls": 0
                        },
                        "satisfaction": -1,
                        "satisfaction_now": -1,
                        "satisfaction_real": -1,
                        "sta_table": [],
                        "state": "RUN",
                        "tx_bytes": 1179901841,
                        "tx_combined_retries": 0,
                        "tx_data_mpdu_bytes": 0,
                        "tx_dropped": 621810,
                        "tx_errors": 621699,
                        "tx_packets": 67980095,
                        "tx_power": 18,
                        "tx_retries": 0,
                        "tx_rts_retries": 0,
                        "tx_success": 0,
                        "tx_tcp_stats": {
                                "goodbytes": 0,
                                "lat_avg": 0,
                                "lat_max": -1,
                                "lat_min": -1,
                                "lat_samples": 0,
                                "lat_sum": 0,
                                "retries": 0,
                                "stalls": 0
                        },
                        "tx_total": 0,
                        "up": true,
                        "usage": "user",
                        "wifi_tx_attempts": 0,
                        "wifi_tx_dropped": 0
                },
                {
                        "anomalies_bar_chart": {
                                "high_disconnect_count": 0,
                                "high_dns_latency": 0,
                                "high_icmp_rtt": 0,
                                "high_tcp_latency": 0,
                                "high_tcp_packet_loss": 0,
                                "high_wifi_latency": 0,
                                "high_wifi_retries": 0,
                                "low_phy_rate": 0,
                                "no_dhcp_response": 0,
                                "poor_stream_eff": 0,
                                "sleepy_client": 0,
                                "sta_arp_timeout": 0,
                                "sta_dns_timeout": 0,
                                "sta_ip_timeout": 0,
                                "weak_signal": 0
                        },
                        "anomalies_bar_chart_now": {
                                "high_disconnect_count": 0,
                                "high_dns_latency": 0,
                                "high_icmp_rtt": 0,
                                "high_tcp_latency": 0,
                                "high_tcp_packet_loss": 0,
                                "high_wifi_latency": 0,
                                "high_wifi_retries": 0,
                                "low_phy_rate": 0,
                                "no_dhcp_response": 0,
                                "poor_stream_eff": 0,
                                "sleepy_client": 0,
                                "sta_arp_timeout": 0,
                                "sta_dns_timeout": 0,
                                "sta_ip_timeout": 0,
                                "weak_signal": 0
                        },
                        "avg_client_signal": 0,
                        "bssid": "redacted",
                        "bw": 40,
                        "ccq": 0,
                        "channel": 40,
                        "dns_avg_latency": -1,
                        "essid": "redacted",
                        "extchannel": -1,
                        "icmp_avg_rtt": -1,
                        "id": "55e56b4c71b08cb47ddd9057",
                        "mac_filter_rejections": 0,
                        "name": "rai0",
                        "num_satisfaction_sta": 0,
                        "num_sta": 0,
                        "radio": "na",
                        "radio_name": "rai0",
                        "reasons_bar_chart": {
                                "no_dhcp_response": 0,
                                "phy_rate": 0,
                                "signal": 0,
                                "sleepy_client": 0,
                                "sta_arp_timeout": 0,
                                "sta_disconnects": 0,
                                "sta_dns_latency": 0,
                                "sta_dns_timeout": 0,
                                "sta_icmp_rtt": 0,
                                "sta_ip_timeout": 0,
                                "stream_eff": 0,
                                "tcp_latency": 0,
                                "tcp_packet_loss": 0,
                                "wifi_latency": 0,
                                "wifi_retries": 0
                        },
                        "reasons_bar_chart_now": {
                                "no_dhcp_response": 0,
                                "phy_rate": 0,
                                "signal": 0,
                                "sleepy_client": 0,
                                "sta_arp_timeout": 0,
                                "sta_disconnects": 0,
                                "sta_dns_latency": 0,
                                "sta_dns_timeout": 0,
                                "sta_icmp_rtt": 0,
                                "sta_ip_timeout": 0,
                                "stream_eff": 0,
                                "tcp_latency": 0,
                                "tcp_packet_loss": 0,
                                "wifi_latency": 0,
                                "wifi_retries": 0
                        },
                        "rx_bytes": 1201068771,
                        "rx_crypts": 0,
                        "rx_dropped": 1021103,
                        "rx_errors": 1034,
                        "rx_frags": 0,
                        "rx_nwids": 0,
                        "rx_packets": 4765596,
                        "rx_tcp_stats": {
                                "goodbytes": 0,
                                "lat_avg": 0,
                                "lat_max": -1,
                                "lat_min": -1,
                                "lat_samples": 0,
                                "lat_sum": 0,
                                "retries": 0,
                                "stalls": 0
                        },
                        "satisfaction": -1,
                        "satisfaction_now": -1,
                        "satisfaction_real": -1,
                        "sta_table": [],
                        "state": "RUN",
                        "tx_bytes": 1129671713,
                        "tx_combined_retries": 0,
                        "tx_data_mpdu_bytes": 0,
                        "tx_dropped": 55,
                        "tx_errors": 0,
                        "tx_packets": 12114126,
                        "tx_power": 18,
                        "tx_retries": 0,
                        "tx_rts_retries": 0,
                        "tx_success": 0,
                        "tx_tcp_stats": {
                                "goodbytes": 0,
                                "lat_avg": 0,
                                "lat_max": -1,
                                "lat_min": -1,
                                "lat_samples": 0,
                                "lat_sum": 0,
                                "retries": 0,
                                "stalls": 0
                        },
                        "tx_total": 0,
                        "up": true,
                        "usage": "guest",
                        "wifi_tx_attempts": 0,
                        "wifi_tx_dropped": 0
                }
        ],
        "version": "6.2.49.14111",
        "wifi_caps": 18792157
}`


Here is the same AP in unifi network console:
![obraz](https://user-images.githubusercontent.com/67835103/236417445-b309a67f-8384-422d-88c5-85f52189328d.png)

**Comment by patricegautier** [comment]
Ok I see the problem..

**Comment by patricegautier** [comment]
Ok try the latest - lmk if it doesn't fix the issue..
