### ISSUE TITLE
mca-dump-short.sh SWITCH_DISCOVERY doesn't work on USW-Enterprise-8-POE

### ISSUE THREAD

**Issue by mrrogers75** [patricegautier/unifiZabbix#105]
Port discovery returns a blank response because the USW-Enterprise-8-POE requires a return sent after telnet 127.0.0.1 to get a prompt, and the prompt is not "(UBNT) >" but the switch name with #. It also doesn't require "enable" to be sent to get the configuration.

See example connection:

Device sw-myswitchname: Connecting
Device sw-myswitchname: Connected

BusyBox v1.25.1 () built-in shell (ash)

  ___ ___      .__________.__
 |   |   |____ |__\_  ____/__|
 |   |   /    \|  ||  __) |  |   (c) 2010-2023
 |   |  |   |  \  ||  \   |  |   Ubiquiti Inc.
 |______|___|  /__||__/   |__|
            |_/                  https://www.ui.com

      Welcome to UniFi USW-Enterprise-8-PoE!

********************************* NOTICE **********************************
* By logging in to, accessing, or using any Ubiquiti product, you are     *
* signifying that you have read our Terms of Service (ToS) and End User   *
* License Agreement (EULA), understand their terms, and agree to be       *
* fully bound to them. The use of SSH (Secure Shell) can potentially      *
* harm Ubiquiti devices and result in lost access to them and their data. *
* By proceeding, you acknowledge that the use of SSH to modify device(s)  *
* outside of their normal operational scope, or in any manner             *
* inconsistent with the ToS or EULA, will permanently and irrevocably     *
* void any applicable warranty.                                           *
***************************************************************************

sw-myswitchname-US.6.5.32# cat /etc/board.info 
board.sysid=0xed41
board.name=USW-Enterprise-8-PoE
board.shortname=US68P
board.subtype=
board.hwaddr=D021F96A4CAB
board.reboot=135
board.upgrade=320
board.phycount=1
board.required_fw_version=5.46.0
sw-myswitchname-US.6.5.32# telnet 127.0.0.1

Entering character mode
Escape character is '^]'.

sw-myswitchname#show running-config 
config-file-header
sw-myswitchname
v1.0.1.0 / ?
CLI v1.0
@
!
unit-type-control-start
unit-type unit 1 network tw uplink te
unit-type-control-end
!
vlan database
vlan 4,73,180-181
exit
dot1x mac-auth eap username groupsize 12 separator : uppercase
no lldp med network-policy voice auto
lldp med network-policy 1 voice vlan 73 vlan-type tagged

**Comment by patricegautier** [comment]
Ok that should be easy to include.. I don't have this model to test, so bear with me:

- does it support 'cli' straight after ssh-ing into it perhaps, rather than having to telnet to 127.0.0.1?   if it does, the same code path as USW-Aggregation or USW-Flex-XG could work..

**Comment by mrrogers75** [comment]
I changed line 229 to:
           -re "(USW-Aggregation|USW-Flex-XG|USW-Enterprise-8-PoE)\r\n" {
and now it works. So yes that is a simple fix.
Thanks

**Comment by patricegautier** [comment]
Sweet!  Change committed..

	-P
