### ISSUE TITLE
Large spikes Channel Interference for U7 Pro

### ISSUE THREAD

**Issue by send2ali** [patricegautier/unifiZabbix#113]
Im having an issues with false channel Interference readings for my recently installed U7 Pro. It jumps from 1-3% to  some very high amount like 4294967172 %. This happens on all three channels on random times. I count about 9 in the last day or so. 
I have other AP's and switch running with no issue.

Nothing is showing up in mcaDumpShort.err or zabbix_server.log for this AP. Only thing of note is that it replaced a different AP and I used the same IP address.  Had some server key errors when I first installed it but I cleared out.

![U7Pro-Error2](https://github.com/patricegautier/unifiZabbix/assets/55221104/d68df4f6-b848-4c70-9395-6412b73516b5)
![U7Pro-Error1](https://github.com/patricegautier/unifiZabbix/assets/55221104/254b3f0e-7fea-4c47-8e74-10cf53fad62c)

Any help would be great.

Im running 
Ubunt 20.4.6 LTS
Zabbix 6.4.13
Using the latest version of your script (from 3 weeks ago)

**Comment by patricegautier** [comment]
Sadly I don't have a U7 Pro I can test with..   My guess is that mca-dump on the AP itself is returning an aberrant value once in a while.   I could stomp the problem and discard any value that is not between 0 and a 100 I just wonder if there's something else going on there before I do that.

**Comment by patricegautier** [comment]
for what it's worth, the channel utilization #s on the 6 enterprise are also very suspicious.  I reported it to Unifi..

**Comment by send2ali** [comment]
I like your stomping idea, sounds like a fix. Not sure how long unifi will take to fix it, if at all.
Im happy if you want me to do any testing on my end as well.

**Comment by patricegautier** [comment]
Well try this latest commit for the template set.  I added range validation to a lot of items, including all the percentages..

**Comment by send2ali** [comment]
Thanks, I've just updated the template. Hopefully should be resolved. I'll report back in day or so.

**Comment by send2ali** [comment]
Reporting back. 
I haven't received a single alert since i updated the template. I'll close this request off. 
Thanks for your help in resolving this issue.
Also i looked a bit further into the alerts and noticed that only two of the three channels were causing this. 
6e and na had the high percentage alerts while the ng channel interference was at normal levels the whole time.
