### ISSUE TITLE
Unsupported Item?

### ISSUE THREAD

**Issue by stevefxp1** [patricegautier/unifiZabbix#122]
Hello,

I imported your YAML today and noticed it generated an unsupported item for each group. Attached is a screenshot of this. The unsupported item is template group called Unifi Zabbix Export. I dont see anything to cause this but I am running Zabbix 7 at this time.

Happy to provide any additional information should you need it.

Thanks,
Steve

![Screenshot 2024-07-17 202059](https://github.com/user-attachments/assets/33fc97ec-b633-4421-ae4d-7c1da898c2a4)
![Screenshot 2024-07-17 201931](https://github.com/user-attachments/assets/da4059e3-b128-44d2-bb62-2cea93a15614)

**Comment by patricegautier** [comment]
Ah that one is legit - it's a template that the other templates inherit from to be able to flag unsupported items that can be good signals that there is an issue.  I will add a bit to the documentation to that effect.
