### ISSUE TITLE
Issues with U7 Pro Max

### ISSUE THREAD

**Issue by send2ali** [patricegautier/unifiZabbix#124]
Hi, I just installed two U7 Pro Max's and having issues with your scrip. 

The Zabbix logs showing the following:

256862:20240927:151256.748 error reason for "10.10.0.27:cpu" changed: Preprocessing failed for: parse error: Invalid numeric literal at line 1, column 7./usr/lib/zabbix/externalscripts/mca-dump...
1. Result: parse error: Invalid numeric literal at line 1, column 7./usr/lib/zabbix/externalscripts/mca-dump...
2. Failed: cannot extract value from json by path "$.['system-stats'].cpu": invalid object format, expected opening character '{' or '[' at: 'parse error: Invalid numeric literal at line 1, column 7
/usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 393: echo: write error: Broken pipe
{ "at":"15:12:56", "r":"validationError

Every item is giving the same error.

Im able to run the script on the Zabbix server and is pulling data successfully. It much more data compared to a U7 Pro. I'm not having issues with any other AP'or switches.

Any help would be great

**Comment by patricegautier** [comment]
how big is the U7 pro max output?  more than 64k?  Zabbix does have a limit there mca-dump works around it before handing the value to zabbix, but the u7 pro max must be adding new info.   If you are willing to send me one of the mac-dump outputs I will take a look,,

**Comment by send2ali** [comment]
The dumps look around 73k to 77k, the file size changes each time I ran it. Lowest I saw it was around 44k. 
The U7-Pro seems to be around 10k.

Sure, I can send you the dumps directly. Let me know how you want it sent.

**Comment by patricegautier** [comment]
Email at ***@***.*** is good..

	-P

**Comment by send2ali** [comment]
looks like your email address got block. Try another way.

**Comment by patricegautier** [comment]
Blocked how?  That’s a new one..

	-P

**Comment by send2ali** [comment]
I see the address like this 

Email at ***@***.*** is good..

**Comment by patricegautier** [comment]
Sneaky GitHub!..   

The email is
Patrice
at
Mac
.com

	-P

**Comment by send2ali** [comment]
ok, just sent it.

**Comment by patricegautier** [comment]
Ok you might try this latest commit for mca-dump  and let me know if that solves it..  I can’t test here unfortunately.

	-P

**Comment by send2ali** [comment]
I still got errors. (see below) but I get a permissions error when I try running the dump manually now. I need to recheck my work again when I back later.

1. Result: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
2. Failed: cannot extract value from json by path "$.['sys_stats'].loadavg_5": invalid object format, expected opening character '{' or '[' at: '/usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe
{ "at":"10:09:24", "r":"jq --indent 0 del (.port_table) |\                                                                                                      del(.radio_table[]?.scan_
1256860:20240928:100924.356 error reason for "10.10.0.27:mem_used" changed: Preprocessing failed for: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
1. Result: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
2. Failed: cannot extract value from json by path "$.sys_stats.mem_used": invalid object format, expected opening character '{' or '[' at: '/usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe
{ "at":"10:09:24", "r":"jq --indent 0 del (.port_table) |\                                                                                                      del(.radio_table[]?.scan_
1256860:20240928:100924.356 error reason for "10.10.0.27:sat" changed: Preprocessing failed for: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
1. Result: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
2. Failed: cannot extract value from json by path "$.satisfaction": invalid object format, expected opening character '{' or '[' at: '/usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe
{ "at":"10:09:24", "r":"jq --indent 0 del (.port_table) |\                                                                                                      del(.radio_table[]?.scan_
1256860:20240928:100924.356 error reason for "10.10.0.27:mem_total" changed: Preprocessing failed for: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
1. Result: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
2. Failed: cannot extract value from json by path "$.sys_stats.mem_total": invalid object format, expected opening character '{' or '[' at: '/usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe
{ "at":"10:09:24", "r":"jq --indent 0 del (.port_table) |\                                                                                                      del(.radio_table[]?.scan_
1256860:20240928:100924.356 error reason for "10.10.0.27:uptime" changed: Preprocessing failed for: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
1. Result: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
2. Failed: cannot extract value from json by path "$.uptime": invalid object format, expected opening character '{' or '[' at: '/usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe
{ "at":"10:09:24", "r":"jq --indent 0 del (.port_table) |\                                                                                                      del(.radio_table[]?.scan_
1256860:20240928:100924.356 error reason for "10.10.0.27:wireless_reception_bandwidth" changed: Preprocessing failed for: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
1. Result: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
2. Failed: cannot extract value from json by path "$.vap_table.[*].rx_bytes.sum()": invalid object format, expected opening character '{' or '[' at: '/usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe
{ "at":"10:09:24", "r":"jq --indent 0 del (.port_table) |\                                                                                                      del(.radio_table[]?.scan_
1256860:20240928:100924.356 error reason for "10.10.0.27:wireless_transmission_bandwidth" changed: Preprocessing failed for: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
1. Result: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
2. Failed: cannot extract value from json by path "$.vap_table.[*].tx_bytes.sum()": invalid object format, expected opening character '{' or '[' at: '/usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe
{ "at":"10:09:24", "r":"jq --indent 0 del (.port_table) |\

**Comment by send2ali** [comment]
this is the perm error:

$ sudo -u root /usr/lib/zabbix/externalscripts/mca-dump-short.sh -d 10.10.0.27 -u admin -i zb_id_rsa -t AP
/usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 73: /tmp/mcaDumpShort.err: Permission denied
/usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 73: /tmp/mcaDumpShort.err: Permission denied
{ "at":"10:18:41", "r":"timeout (124)", "device":"10.10.0.27", "mcaDumpTimeout":"Error" }


:/usr/lib/zabbix/externalscripts$ ls -lsa
total 52
 4 drwxr-xr-x 2 zabbix zabbix  4096 Sep 28 10:02 .
 4 drwxr-xr-x 5 root   root    4096 Sep 22  2021 ..
20 -rwxr-xr-x 1 root   root   19629 Sep 28 09:59 mca-dump-short.sh
20 -rwxr-xr-x 1 root   root   18752 Sep 28 09:57 mca-dump-short.sh.bk
 4 -rwxrwxrwx 1 zabbix zabbix  1678 Mar 30 13:57 ssh-run.sh

**Comment by patricegautier** [comment]
So it’s complaining about permissions on /tmp/mcaDumpShort.err

What does ls -l  /tmp/mcaDumpShort.err look like?

	-P{

**Comment by send2ali** [comment]
Hey I think your updated mca dump might be broken. When I try to use it, it break for all my unification devices.

I see theses in the server logs:

1256860:20240928:220846.943 error reason for "10.10.0.12:uptime" changed: Preprocessing failed for: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
1. Result: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
2. Failed: cannot extract value from json by path "$.uptime": invalid object format, expected opening character '{' or '[' at: '/usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe
{ "at":"22:08:46", "r":"jq --indent 0 del (.port_table) |\                                                                                                      del(.radio_table[]?.scan_
1256860:20240928:220846.943 error reason for "10.10.0.12:wireless_reception_bandwidth" changed: Preprocessing failed for: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
1. Result: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe.{ "at...
2. Failed: cannot extract value from json by path "$.vap_table.[*].rx_bytes.sum()": invalid object format, expected opening character '{' or '[' at: '/usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 439: echo: write error: Broken pipe
{ "at":"22:08:46", "r":"jq --indent 0 del (.port_table) |\


This is what my scrip folder and error log look like.

:/usr/lib/zabbix/externalscripts$ ls -lsa
total 52
 4 drwxr-xr-x 2 zabbix zabbix  4096 Sep 28 22:10 .
 4 drwxr-xr-x 5 root   root    4096 Sep 22  2021 ..
20 -rwxr-xr-x 1 zabbix zabbix 18752 Sep 28 09:57 mca-dump-short.sh
20 -rwxrwxrwx 1 zabbix zabbix 19685 Sep 28 21:54 mca-dump-short.sh.broken
 4 -rwxrwxrwx 1 zabbix zabbix  1678 Mar 30 13:57 ssh-run.sh

:/usr/lib/zabbix/externalscripts$ ls -l  /tmp/mcaDumpShort.err
-rw-rw-r-- 1 zabbix zabbix 6679855 Sep 28 22:09 /tmp/mcaDumpShort.err


When i rollback to the old script it all started working again. 

This could be a issue with me as I've been playing around with this a bit, just to let you know I've done the following to get your updated script.

sudo curl -o mca-dump-short.sh https://raw.githubusercontent.com/patricegautier/unifiZabbix/master/mca-dump-short.sh
sudo chmod a+x /usr/lib/zabbix/externalscripts /usr/lib/zabbix/externalscripts/mca-dump-short.sh
sudo chown zabbix:zabbix /usr/lib/zabbix/externalscripts /usr/lib/zabbix/externalscripts/mca-dump-short.sh
sudo chmod 777 mca-dump-short.sh  (didn't need to to this... )

**Comment by patricegautier** [comment]
Good news, I see the same problem here.  Stay tuned.

**Comment by patricegautier** [comment]
Try this latest..

**Comment by send2ali** [comment]
The updated script looks to have resolved the issues, all working now. Had it running for an hour or so. 
Thanks for your help with all this :-)

**Comment by send2ali** [comment]
Updated script is now working with the new U7 Pro Max AP's
