### ISSUE TITLE
mca-dump-short.sh fails on jq

### ISSUE THREAD

**Issue by zpolisensky** [patricegautier/unifiZabbix#125]
Hey,
I just wanted to let you know that I discovered a problem with Zabbix 7 and the latest version of the Unifi scripts (it may be more of a Zabbix problem, I don't know to be honest, but there is a solution at the end).

The mca-dump-short.sh script returns an error:
{ "at":"08:07:48", "r":"jq --indent 0 del (.port_table[]?.mac_table) returned status 5; jq: parse error: Invalid numeric literal at line 1, column 8", "device":"10.0.1.5", "mcaDumpError":"Error" }

I found out that it's because the output is not clear JSON, but there is one more sentence at the beginning (/var/lib/zabbix is home folder for my Zabbix):
_Warning: Identity file /var/lib/zabbix/.sshid_rsa not accessible: No such file or directory._

This file does not exist because my keys are in /var/lib/zabbix/.ssh/
Strange that it is throwing this error but still able to connect and collect data (but messing with the json file).

Anyway, the solution (let's call it a workaround) is quite simple and it's a symbolic link:
ln -s /var/lib/zabbix/.ssh/id_rsa /var/lib/zabbix/.sshid_rsa

Hope this helps someone.
Zbynek

**Comment by patricegautier** [comment]
looks like someone is ssh land is not heeding the -o LogLevel=Error directive unfortunately.  I don't think this is worth writing stderr down to a file for just this case, so just closing this and hoping that other people who run into this will find this workaround.
