### ISSUE TITLE
Cloud Key G2 Plus - mca-dump: command not found

### ISSUE THREAD

**Issue by d4v3r0y** [patricegautier/unifiZabbix#126]
### Cloud Key Gen 2 Plus:
This is likely a me issue, but I'm as to the status of support for Cloud Key devices at this time due to them not having mca-dump installed. The readme shows CK, but some of the support cases (that are older) say it's not. Anyway, I'm running `sudo -u zabbix /usr/lib/zabbix/externalscripts/mca-dump-short.sh -d 10.10.1.10 -u SSH-USER -i /home/zabbix/.ssh/zb_id_rsa -t CK` and getting the error "mca-dump: command not found." 

Here is the output of the command.

[error.txt](https://github.com/user-attachments/files/18255621/error.txt)

SSH works with the CKG2+ itself with the example - sudo -u zabbix ssh -i <fullPathToYourPrivateKey> yourUserName@oneOfYourUnifiDevicesIP 

I have this working on our aggregation switch, but would prefer it to work on the CKG2+ if at all possible. 

### WifiSite
If you do not have an AP group, is there a default to use or should one be created? 

I appreciate the work that has been done on this. It's awesome and a great help to look pretty numbers and you know, monitoring and such. 

Thank you!!!

**Comment by patricegautier** [comment]
cloud key themselves are not directly supported at this time I'm afraid..  You are right there were some inconsistencies in the project wrt that.  I am cleaning those up :)

The only templates you can use from this project is 'Unifi SSH Host' and/or 'Unifi Protect Cloud Key' for the protect aspects if you use that

**Comment by patricegautier** [comment]
You do need to create the group in Zabbix for the APs in the site, none is there by default..

**Comment by d4v3r0y** [comment]
I'm still unable to get WifiSite to work. 

`root@ubuntu:/usr/lib/zabbix/externalscripts# sudo -u zabbix /usr/lib/zabbix/externalscripts/mca-dump-short.sh -d 10.10.1.50 -v -u SSHUSER -i /home/zabbix/.ssh/zb_id_rsa -t WIFI_SITE
Unknown device Type: 'WIFI_SITE'
Usage /usr/lib/zabbix/externalscripts/mca-dump-short.sh  -i privateKeyPath -p <passwordFilePath> -u user -v -d targetDevice [-t AP|SWITCH|SWITCH_FEATURE_DISCOVERY|SWITCH_DISCOVERY|UDMP|UDMP_FAN_DISCOVERY|UDMP_TEMP_DISCOVERY|USG|USG-LITE|CK|WIFI_SITE]
  -i specify private public key pair path
  -p specify password file path to be passed to sshpass -f. Note if both -i and -p are provided, the password file will be used
  -u SSH user name for Unifi device
  -d IP or FQDN for Unifi device
  -o alternate port for SSH connection
  -t Unifi device type
  -v verbose and non compressed output
  -w verbose output for port discovery
  -x extreme debugging
  -o <timeout> max timeout (3s minimum)
  -O echoes debug and timing info to /tmp/mcaDumpShort.log; errors are always echoed to /tmp/mcaDumpShort.err
  -V <jqExpression> Provide a JQ expression that must return a non empty output to validate the results. A json error is returned otherwise
  -b run SSH in batch mode (do not ask for passwords)
`

Connecting to individual APs works fine.

Let me know if you see something wrong here.
![image](https://github.com/user-attachments/assets/854b9983-8137-4fcb-bb61-ff1f20cf396f)
![image](https://github.com/user-attachments/assets/55857914-2c4e-49a6-968a-4d607edc8c7d)
![image](https://github.com/user-attachments/assets/1e8423b6-0faa-4909-af02-d7321a2c79b2)
![image](https://github.com/user-attachments/assets/f5706999-fa05-4bd7-9007-37c38267730c)
![image](https://github.com/user-attachments/assets/b1a06db3-0cf6-4db6-b8a3-01f7ea76267d)
![image](https://github.com/user-attachments/assets/748cd23b-e638-406c-82f0-4f7fcc886d56)
![image](https://github.com/user-attachments/assets/8fe9fa64-aa8a-4bb1-9fa9-a88b2d4190f5)
![image](https://github.com/user-attachments/assets/80e5b400-78da-434a-abf0-50d31f6008b8)
![image](https://github.com/user-attachments/assets/2a63b7dd-6923-4695-976e-59d99d14e152)
![image](https://github.com/user-attachments/assets/17455ad3-a8a7-4be2-bd31-92c8792a4c2c)
![image](https://github.com/user-attachments/assets/1ddd7f34-82c7-4f5a-ae57-a3b948c6e131)
