### ISSUE TITLE
How can I use Wifi site?

### ISSUE THREAD

**Issue by midworld** [patricegautier/unifiZabbix#14]
Hi guys, thank you for the great configuration template.

I am trying to add Wifi site template to one of my AP but it couldn't.

![image](https://user-images.githubusercontent.com/1697772/121790430-3e37ea80-cc1a-11eb-9b14-6d0a2b477681.png)

It says `Item "mca-dump-short.sh["-d","{HOST.CONN}", "-u", "{$UNIFI_USER}", "-i", "{$UNIFI_SSH_PRIV_KEY_PATH}", "-t", "AP"]" already exists on "Home AP", inherited from another template.`.

There is no problem with my AP and USG but just Wifi site. Please help.

Thanks!

**Comment by patricegautier** [comment]
I think the documentation isn't quite clear enough on the WiFi site.  You have to create a separate host (and call it 'My Site' or some such) and point it to the IP of one of the APs..

as an example:

<img width="797" alt="image" src="https://user-images.githubusercontent.com/38435239/121982657-c31f2300-cd44-11eb-9586-bef6530cd677.png">

I'll touch up the doc.

**Comment by midworld** [comment]
Hi, thank you for the fast response.

I set my all APs within 2F host group:

![image](https://user-images.githubusercontent.com/1697772/122024806-bc0b1a00-ce03-11eb-9105-4f8aeded2bb2.png)

and my site has those templates and a macro:

![image](https://user-images.githubusercontent.com/1697772/122024946-dfce6000-ce03-11eb-892d-20e159ee647b.png)
![image](https://user-images.githubusercontent.com/1697772/122025050-fa083e00-ce03-11eb-954e-2c11409ac1d5.png)

But it shows just a load graph. I couldn't see the bandwidth data.

![image](https://user-images.githubusercontent.com/1697772/122024559-81a17d00-ce03-11eb-86d7-a880c90e9bc1.png)

Is my setting wrong?

Thanks!

**Comment by patricegautier** [comment]
If you go to ‘Latest Data’ or look at the items for that Wifi Site 2F host what do you see?

	-P

**Comment by patricegautier** [comment]
Ok go the configuration of Wifi Site 2F, and them to the items tab, does it show any error there?

	-P

**Comment by midworld** [comment]
Oh there are some errors:
![image](https://user-images.githubusercontent.com/1697772/122720703-c2d5d900-d2aa-11eb-8feb-6d00815e3b3b.png)
with message:
`Cannot evaluate function: no items matching query at "avg_foreach(/*/rx_bandwidth[kongstudios-guest]?[group="{$AP_GROUP}"],{$UNIFI_SMOOTHING_PERIOD}))".`

My site host has the following item:
![image](https://user-images.githubusercontent.com/1697772/122720944-07fa0b00-d2ab-11eb-8738-201a2b558bbe.png)
and now I just added `{$AP_GROUP}`:
![image](https://user-images.githubusercontent.com/1697772/122721158-4b547980-d2ab-11eb-9f1f-e98b80f228ec.png)

Voilà! Now I can see the graph!!!
![image](https://user-images.githubusercontent.com/1697772/122721273-6de69280-d2ab-11eb-99dc-41f3f27ea2f7.png)

README needs to be updated. Thank you for your help!!!

**Comment by patricegautier** [comment]
Will do, thank you

**Comment by DRK-Boll** [comment]
Hi Patrice what does the Wifi Site Plugin do? How can i configurate it for other system?

Thanks
