### ISSUE TITLE
Script timeout: No data, network discovery failing w error

### ISSUE THREAD

**Issue by ChrisMZ** [patricegautier/unifiZabbix#16]
First of all thank you so much for your work!

I'm running Zabbix 5.4.1 (mysql) in Docker and completed all steps from your wiki. 
I added hosts for my USG and 2 APs and for all of them I get the "_...has not reported statistics for 5m_"-problem.

The only data collected successfully is Load Avg, Ping and uname. 
However the SSH setup & external script seem to work in gerneral as I get all the values when I do 
_sudo -u zabbix /usr/lib/zabbix/externalscripts/mca-dump-short.sh -d <theDeviceIP> -u <yourUnifiUserName> -i <fullPathToYourPrivateKey> -t <UDMP|AP|SWITCH|CK>_
manually from within the container.

When I try to execute the Network Discovery for a Unifi host manually in Zabbix the following error is returned:
_Cannot send request: wrong discovery rule type._

The rule type is set to _Dependent item_ and I cannot change this (I think this should be correct anyway).

From the Logfile:

_203:20210726:090344.218 Failed to execute command "/usr/lib/zabbix/externalscripts/mca-dump-short.sh '-d' '192.168.1.1' '-u' 'chris' '-i' '/var/lib/zabbix/ssh_keys' '-t' 'USG'": Timeout while executing a shell script._ 

Rights on the script are 
-rwxr-xr-x    1 zabbix   zabbix        1409 Jul 26 08:50 mca-dump-short.sh

Do you have an idea whats going on? 

PS: When executing the ssh command from the script manually I get

 _zabbix/ssh_keys/zb_id_rsa chris@$192.168.1.1 "mca-dump | gzip" | gunzip | jq --indent 0 "del (.dpi_stats) | del(.fingerprints)"
ssh: connect to host 92.168.1.1 port 22: Operation timed out

gzip: stdin: unexpected end of file_

Cheers
Chris

**Comment by ChrisMZ** [comment]
UUUUuh nevermind xD

I forgot to attach the actual key-file name to the path of {$UNIFI_SSH_PRIV_KEY_PATH}

Cheers
Chris

**Comment by patricegautier** [comment]
So does this mean it's now working :) ?

**Comment by ChrisMZ** [comment]
Yes. Everything works like a charm :)
Thanks again for sharing this!



Patrice ***@***.***> schrieb am Di., 27. Juli 2021, 18:08:

**Comment by patricegautier** [comment]
My pleasure!
