### ISSUE TITLE
Generate SSH Key

### ISSUE THREAD

**Issue by tocks53** [patricegautier/unifiZabbix#17]
Hello, sorry but i don't understand the how to for the ssh key

in my zabbix in enter :

administrateur@S-Zabbix-1:~$ pwd
/home/administrateur
administrateur@S-Zabbix-1:~$ sudo -u zabbix ssh-keygen -P "" -t rsa  -m pem -f zb_id_rsa
Generating public/private rsa key pair.
Saving key "zb_id_rsa" failed: Permission denied
administrateur@S-Zabbix-1:~$

administrateur@S-Zabbix-1:~/.ssh/zabbix$ ls -l
total 0
administrateur@S-Zabbix-1:~/.ssh/zabbix$

I am on debina 10.

Can you explain the methode to create the good ssh key ?

Thanks

**Comment by patricegautier** [comment]
looks to me the Zabbix user does not have permission to /home/administrateur/.ssh

That's why I created  /home/administrateur/.ssh/zabbix, gave the Zabbix user the ownership and right permissions to that and then and put the keys in there.  On my system this looks like:

pi@pi4992:~/.ssh/zabbix $ ls -al
total 28
-rw-r--r-- 1 zabbix zabbix  391 Jul 23  2020 zb_id_rsa.pub
-rw------- 1 zabbix zabbix 1675 Jul 23  2020 zb_id_rsa
drwxr-xr-x 2 zabbix zabbix 4096 Sep 13  2020 .
drwxr-xr-x 3 pi     pi     4096 Mar  1 13:54 ..

ou alors on peut le faire en Français :) ?

**Comment by patricegautier** [comment]
I updated the docs to make that more clear

**Comment by tocks53** [comment]
Salut,

effectivement avec la modification de la documentation, les key sont bien généré.

`administrateur@S-Zabbix-1:~/.ssh/zabbix$ ls -l
total 8
-rw------- 1 zabbix zabbix 1679 août  11 09:39 zb_id_rsa
-rw-r--r-- 1 zabbix zabbix  399 août  11 09:39 zb_id_rsa.pub
administrateur@S-Zabbix-1:~/.ssh/zabbix$`


J'ai bien ajouté zb_id_rsa.pub dans la console unifi dans site.

Mais lorsque je test la connections vers une borne wifi :
```
administrateur@S-Zabbix-1:~$ sudo -u zabbix ssh -i /home/administrateur/.ssh/zabbix/zb_id_rsa zabbix@192.168.53.235                                            [sudo] Mot de passe de administrateur : 
Could not create directory '/var/lib/zabbix//.ssh'.
The authenticity of host '192.168.53.235 (192.168.53.235)' can't be established.
RSA key fingerprint is SHA256:18iESiAWRvmsA4nKajARXGSHAMlDIKd1C7b42EWAliE.
Are you sure you want to continue connecting (yes/no)?

```

Pourrais tu développer la suite ?

Cordialement,

**Comment by patricegautier** [comment]
> The authenticity of host '192.168.53.235 (192.168.53.235)' can't be established.
> RSA key fingerprint is SHA256:18iESiAWRvmsA4nKajARXGSHAMlDIKd1C7b42EWAliE.
> Are you sure you want to continue connecting (yes/no)?

Que se passe-t-il après ca?

> Could not create directory '/var/lib/zabbix//.ssh'.

Et si tu le crée celui-la?



	-P

**Comment by tocks53** [comment]
salut,

j'ai donc créer les répertoires :

`administrateur@S-Zabbix-1:~$ sudo mkdir /var/lib/zabbix/
[sudo] Mot de passe de administrateur : 
administrateur@S-Zabbix-1:~$ sudo mkdir /var/lib/zabbix/.ssh
administrateur@S-Zabbix-1:~$`



puis :

`administrateur@S-Zabbix-1:~$ sudo -u zabbix ssh -i /home/administrateur/.ssh/zabbix/zb_id_rsa zabbix@192.168.53.235
The authenticity of host '192.168.53.235 (192.168.53.235)' can't be established.
RSA key fingerprint is SHA256:18iESiAWRvmsA4nKajARXGSHAMlDIKd1C7b42EWAliE.
Are you sure you want to continue connecting (yes/no)? yes
Failed to add the host to the list of known hosts (/var/lib/zabbix/.ssh/known_hosts).
zabbix@192.168.53.235's password:`


il me demande le mot de passe pour connecter en ssh.

**Comment by tocks53** [comment]
Mais comment vérifier que ma key public est bien arrivé sur la borne wifi ?

**Comment by patricegautier** [comment]
Did you do:

sudo -u zabbix ssh-copy-id -i <path_to_your_privateKey> ***@***.***
And did that give any error?

You can check the private key is there by ssh-ing into the target UniFi device and looking at:

/etc/dropbear/authorized_keys


	-P

**Comment by tocks53** [comment]
sudo -u zabbix ssh-copy-id -i <path_to_your_privateKey> ***@***.***
pas d'erreur :

`administrateur@S-Zabbix-1:~$ sudo -u zabbix ssh-copy-id -i /home/administrateur/.ssh/zabbix/zb_id_rsa admin@192.168.53.235
[sudo] Mot de passe de administrateur : 
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/administrateur/.ssh/zabbix/zb_id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
admin@192.168.53.235's password:

Number of key(s) added: 1

Now try logging into the machine, with:   "ssh 'admin@192.168.53.235'"
and check to make sure that only the key(s) you wanted were added.`


`root@S-Zabbix-1:~# sudo -u zabbix ssh -i /home/zabbix/.ssh/zb_id_rsa admin@192.168.53.235


BusyBox v1.25.1 () built-in shell (ash)


  ___ ___      .__________.__
 |   |   |____ |__\_  ____/__|
 |   |   /    \|  ||  __) |  |   (c) 2010-2020
 |   |  |   |  \  ||  \   |  |   Ubiquiti Networks, Inc.
 |______|___|  /__||__/   |__|
            |_/                  https://www.ui.com/

      Welcome to UniFi UAP-AC-Pro-Gen2!

Bureau-BZ.v4.3.28#
`
Je pense que dans la doc, sur la ligne :

`sudo -u zabbix ssh -i <fullPathToYourPrivateKey> yourUserName@oneOfYourUnifiDevicesIP`

la mention yourUserName correspond au nom indiqué dans le contrôleur unifi pour le ssh. cela m'a induit en erreur, je mettais zabbix.

Merci pour ton aide.

Je continue mes tests.
