### ISSUE TITLE
Switch-2 SSH has not been available for more than 10m

### ISSUE THREAD

**Issue by tocks53** [patricegautier/unifiZabbix#18]
Bonjour,

J'ai ajouté 32 équipements Unifi.

J'ai régulièrement des erreur sur  SSH has not been available for more than 10m

Après analyse, c'est les valeurs de Load Average qui ne s'actualise pas forcément des les 10 mins

![image](https://user-images.githubusercontent.com/7701808/129442397-76a489d5-9c57-483d-930f-e60e5b81722a.png)

![image](https://user-images.githubusercontent.com/7701808/129442426-faa03857-53b7-4c53-8504-eda91a7b56de.png)

pas d'erreurs sur les autres valeurs :

![image](https://user-images.githubusercontent.com/7701808/129442440-bfd47872-84cc-4353-bc5e-c20b29d11366.png)

As tu une idées pourquoi les Load Average ne s'actualisent pas correctement dans les 10 min ?

Merci pour ton expertise

ps : bravo pour ta super intégration de unifi dans zabbix. En amélioration, ne pourrait on pas récupérer le nom des ports des switchs configuré dans l'interface de unifi ?

**Comment by patricegautier** [comment]
Quand tu vas sur la configuration des items d'un des switch qui a le problème, que vois-tu comme erreur sur le load average?

Pour ce qui est du nom, bonne idée, je vais regarder si je peux l'attraper..

**Comment by patricegautier** [comment]
Ca pourrait être ce problème SSH (from the readme): 

> • if some of your items randomly fail with 'Cannot read data from SSH server' (in the UI or in /var/log/zabbix/zabbix_server.log), the likely culprit is an outdated version of libssh, which sometimes returns an error code even on success. You have to compile the last version from sources from libssh.org and recompile I'm afraid.. This was a problem on Raspbian buster for libssh 0.8.x and is confirmed fixed with libssh 0.9.5 at least.

v

**Comment by tocks53** [comment]
Bonjour,
Je ne constate pas d'erreur sur le load average

![image](https://user-images.githubusercontent.com/7701808/129713769-4be84846-d5bc-4eff-b6d9-c550545550bf.png)

![image](https://user-images.githubusercontent.com/7701808/129713825-5ba89310-cc4c-4448-9a5c-e672d460a089.png)

![image](https://user-images.githubusercontent.com/7701808/129713875-eebdb793-e113-47e4-a0a5-f38732f172c9.png)


avec en erreur sur le ! rouge : Cannot read data from SSH server


`root@S-Zabbix-1:~# apt-show-versions libssh
libssh not installed (not available)
root@S-Zabbix-1:~#
`

`root@S-Zabbix-1:~# apt-cache policy libssh
libssh2-1          libssh2-1-dev      libssh-4           libssh-dev         libssh-doc         libssh-gcrypt-4    libssh-gcrypt-dev
root@S-Zabbix-1:~# apt-cache policy libssh
`
`root@S-Zabbix-1:~# apt-cache policy libssh-4
libssh-4:
  Installé : 0.8.7-1+deb10u1
  Candidat : 0.8.7-1+deb10u1
 Table de version :
 *** 0.8.7-1+deb10u1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
root@S-Zabbix-1:~#
`

je suppose donc que la version libssh en 0.8.7-1 n'est pas suffisante ?

**Comment by lslamp** [comment]
@tocks53 
Sorry I do not speak French, but reading through your ssh issues it seems that we are fighting something very similar.
If you read my tag you will see from my logs that the issue seems to be from the unifi devices and not from the zabbix server.

Any further ideas?
Lawrence

**Comment by tocks53** [comment]
@lslamp, i comment on your issues

**Comment by tocks53** [comment]
j'ai donc installé la version 9.5

`root@S-Zabbix-1:~# dpkg -i libssh-4_0.9.5-1_amd64.deb
(Lecture de la base de données... 31891 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de libssh-4_0.9.5-1_amd64.deb ...
Dépaquetage de libssh-4:amd64 (0.9.5-1) sur (0.8.7-1+deb10u1) ...
Paramétrage de libssh-4:amd64 (0.9.5-1) ...
Traitement des actions différées (« triggers ») pour libc-bin (2.28-10) ...
root@S-Zabbix-1:~# apt-cache libssh-4
E: L'opération libssh-4 n'est pas valable
root@S-Zabbix-1:~# apt-cache policy libssh-4
libssh-4:
  Installé : 0.9.5-1
  Candidat : 0.9.5-1
 Table de version :
 *** 0.9.5-1 100
        100 /var/lib/dpkg/status
     0.8.7-1+deb10u1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
root@S-Zabbix-1:~#

je vais donc attendre pour check si c'est mieux
`

**Comment by tocks53** [comment]
Je confirme que après l'installation de libssl 0.9.5 tout est ok pour moi sur les erreur ssh

https://packages.debian.org/bullseye/amd64/libssh-4/download

Il faudrait peut être rajouter cela dans la documentation.

Thanks

**Comment by patricegautier** [comment]
Bonne nouvelle!

C’est déjà mentionné dans la doc :)

	-P

**Comment by patricegautier** [comment]
Added a reference to the download link to troubleshooting section
