### ISSUE TITLE
Error on 	US-16-XG

### ISSUE THREAD

**Issue by tocks53** [patricegautier/unifiZabbix#19]
Bonjour,

J'ai plusieurs erreurs avec les switchs US-16-XG

cela pour les items sur la consommation électrique. Mais ce switch n'est pas POE.

![image](https://user-images.githubusercontent.com/7701808/129768686-309cd4bc-9598-46af-aeb2-32cd95ec178f.png)

![image](https://user-images.githubusercontent.com/7701808/129768723-1d98abb4-bd66-4071-a39f-4dab2153904d.png)

Je n'ai pas ces erreur sur les switch POE.

Peux améliore la découverte, pour ne pas les mettre sur ces switchs ?

Cordialement,

**Comment by patricegautier** [comment]
Check out the latest commits.  All the POE stuff has been moved to a discovery rule, which should remove those errors.

Please note you will need to update mca-dump-short and add a new script ssh-run to be accessible by zabbix.  Check out the doc update & let me know if you have any issues..

**Comment by patricegautier** [comment]
Closing - I think this is solved
