### ISSUE TITLE
Fan discovery question

### ISSUE THREAD

**Issue by luponata** [patricegautier/unifiZabbix#20]
Hello!, has anyone tried to implement the Fan discovery ?

My Switch has fans and the mca-dump shell script output shows this informations:

```
... "has_eth1":false,"has_fan":true,"has_speaker":false,"has_temperature":true, ...

... "dualboot":true,"ever_crash":false,"fan_level":0,"fw_caps":592109093, ...
```

Where you can clearly see: **"has_fan"=true** and **"fan_level":0**

I tried playing with the template by cloning one of the existing Discovery rules without success, but for example:

The "Temperature Discovery" rule has this preprocessing option: **$[?(@.has_temperature=="true")]** and the mca-dump output looks the same, but I didn't have any more time to devote to it last night

**Comment by patricegautier** [comment]
That's pretty easy to add.. coming up.

**Comment by patricegautier** [comment]
tada!  check out release 1.1b3.

**Comment by luponata** [comment]
Unfortunately, the parent discovery "**mca-dump-feature-discovery**" item's output doesn't include the fan key that the preprocessing rule is trying to find: **$[?(@.has_fan=="true")]**

`[{"power":true,"total_power_consumed_key_name":"total_power_consumed","max_power_key_name":"max_power","max_power":135,"percent_power_consumed_key_name":"percent_power_consumed","has_eth1":false,"has_temperature":true,"temperature_key_name":"temperature","overheating_key_name":"overheating"}]`

and the error is: 
```
Preprocessing failed for: [{"power":true,"total_power_consumed_key_name":"total_power_consumed","max_power_key_name":"max_p...
1. Failed: cannot extract value from json by path "$[?(@.has_fan=="true")]": no data matches the specified path
```

Should we switch to the discovery item "mca-dump" instead ?

**Comment by patricegautier** [comment]
Did you make sure and update the mca-dump-short.sh script on the zabbix server?

I should have mentioned that in the release notes..

**Comment by luponata** [comment]
Forgot it!, now it works!

Thanks
