### ISSUE TITLE
Does this also work via Zabbix-proxy

### ISSUE THREAD

**Issue by RemcoVroman** [patricegautier/unifiZabbix#21]
Hi,

Thanks for sharing this it is realy great. However my UDM is behind a Zabbix-proxy. Does this work behind a proxy as well ? If not, I can provide a test setup and can make myself available to make this work.

Best regards,
Remco

**Comment by patricegautier** [comment]
not 100% sure about your question:  the templates are meant to be installed on a Zabbix server.  That Zabbix server can in turn collect data from any number of zabbix proxies it is connected to and that will work just fine.  For what it's worth, I have one proxy connected and it's monitoring a number of Unifi devices no problem.

Is that what you meant?

**Comment by patricegautier** [comment]
closing this - not sure there's an issue there.
