### ISSUE TITLE
UDM Pro show switchport traffic

### ISSUE THREAD

**Issue by Mindless999** [patricegautier/unifiZabbix#22]
I would like to monitor a per-port traffic; to see how much traffic has been done per device connected to the UDM.

At this moment you can only see the bandwidth usage for the internet, and not local network traffic. (only the inter-vlan)

**Comment by patricegautier** [comment]
good point - the UDM has an 8 port switch in it.. that is straigthforward to add stay tuned.

**Comment by patricegautier** [comment]
Check out 1.2b1 it should do the trick

**Comment by Mindless999** [comment]
Thanks Patrice, it works like a charm. One of the things I changed in my profile though is that the informational warning that a port is above 25% is not useful for me. I changed it for myself to 75%

**Comment by patricegautier** [comment]
Right, I should probably macro-ize those levels..

It’s on the list.

	-P
