### ISSUE TITLE
Cannot Assign Template

### ISSUE THREAD

**Issue by mighty-services** [patricegautier/unifiZabbix#23]
Dear nerds!

Thank you so much for this template, it will save me a ton of time - once I've got it running :)
I'm new in the zabbix-world and got some things monitored already (like Linux servers and Windows Clients/Servers). Now I want to step into monitoring my Unifi equipment and found your amazing and UPDATED set of templates.

I followed your explanation. I've set up the two sh-skripts in the server, restarted the server, imported the most recent xml-template file and now want to add it to my previously auto-discovered USG/CloudKey. The error I got is this one:

on my USG when I add the USG template only
![image](https://user-images.githubusercontent.com/71066192/138232950-7fa7e30e-539b-4252-994d-0d09e76364cf.png)

and when I add the recommended SSH-Teplamte as well
![image](https://user-images.githubusercontent.com/71066192/138233096-e32e2415-3609-42bf-944a-df934fd9254a.png)

Linking only the ssh template works:
![image](https://user-images.githubusercontent.com/71066192/138233233-3af14163-8e01-4d99-96f8-8313011d1ba2.png)

But when I want to add the USG template after that, it gives me the same error:
`Two items ("Hostname" and "System name") cannot populate one host inventory field "Name", this would lead to a conflict.`

I´m running Zabbix-server 5.4.5 and this is the host-overview of my usg:
![image](https://user-images.githubusercontent.com/71066192/138233696-9ab92beb-7254-46ad-8a9b-b0e4f3749c2c.png)

**Comment by patricegautier** [comment]
Which release are you using?  I think you might be using an old version.. I just stamped v1.2, might be a good time to update!
