### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by Seqway** [patricegautier/unifiZabbix#24]
Hello,
i followed the instructions and so far so well - by the way great effort to make this available for everyone.

I refer to "Setup SSH from your Zabbix server to your Unifi devices via public/private keypair" and here number 3) second command:

`sudo -u zabbix /usr/lib/zabbix/externalscripts/mca-dump-short.sh -d <theDeviceIP> -u <yourUnifiUserName> -i <fullPathToYourPrivateKey> -t <UDMP|AP|SWITCH|CK>`

i arranged it according to my needs and i get the following errormessage:
`syntax error near unexpected token `newline'`

Can you help what is wrong here ?

**Comment by patricegautier** [comment]
solved in the Unifi community thread - you had to pick one of the types for the -t option
