### ISSUE TITLE
ssh login on Unifi Switch or USG

### ISSUE THREAD

**Issue by Seqway** [patricegautier/unifiZabbix#25]
Hello,
as i wrote in the other Issue i have also the problem that ssh login gives me always the prompt:

ECDSA key fingerprint is SHA256:heremykey.
Are you sure you want to continue connecting (yes/no)?

I have to put in YES and then i am still asked to my password. When i enter it i am on the console of Switch or USG.

What did i wrong here ?

**Comment by patricegautier** [comment]
solved this way:

Could not create directory '/var/lib/zabbix//.ssh'.
yes let's fix that. On your zabbix host, you should create the directory /var/lib/zabbix/.ssh and make sure the zabbix user and access and write to it
