### ISSUE TITLE
Testing script is unsuccessful with JQ error

### ISSUE THREAD

**Issue by JAARS-RW** [patricegautier/unifiZabbix#26]
Hello,
I'm running into trouble getting setup.
I've tested the passwordless SSH connection with one of my devices and it works, but when I try to test the script I get this error from JQ:
jq: error (at <stdin>:842): Cannot iterate over null (null)
I tried looking back through others issues but haven't seen anything else that seems related. I've checked the logs and don't seem to see anything indicating a problem with the SSH connection.
Has anyone else encountered this?

**Comment by Seqway** [comment]
No i hadn't that problem and i got it working following step by step this instructions !
And it worked 100%
Did you tried as stated in the docu to test from console the login and getting backing the json ?

**Comment by JAARS-RW** [comment]
Yes, that's what I'm running into trouble with here. When I run
`sudo -u zabbix /usr/lib/zabbix/externalscripts/mca-dump-short.sh -d <theDeviceIP> -u <yourUnifiUserName> -i <fullPathToYourPrivateKey> -t <UDMP|AP|SWITCH|CK>`
with the appropriate values filled in I get the "Cannot iterate over null" error.

**Comment by Seqway** [comment]
Same mistake than i have also done :-)

Your command at the end you habe to tell Only the device

So change from

<UDMP|AP|SWITCH|CK>

To

AP

When you you want to ask an AccessPoint 

😬

**Comment by JAARS-RW** [comment]
I thought I did that? Maybe I chose the wrong one for the IP address I chose.
I'm running it in a VM so I restored the checkpoint from before I tried setting this up and started over (being extra careful this time) and now it's working. Sorry to bother you. I don't really know exactly what I messed up, but I must have missed something.
