### ISSUE TITLE
zabbix server running as container

### ISSUE THREAD

**Issue by panks21** [patricegautier/unifiZabbix#27]
Sorry.. not an issue but question

Any readme guide when zabbix is running as a docker container??

**Comment by patricegautier** [comment]
I am running in a container and it's all working no problem.  You do have keep in mind all the SSH requests are initiated from inside the container when setup the public/private keypairs.. I will add something to the readme.

**Comment by patricegautier** [comment]
Added more info in the README - let me know if this doesn't get you going..

**Comment by panks21** [comment]
thanks a lot
