### ISSUE TITLE
Preprocessing Failed

### ISSUE THREAD

**Issue by BennyDaBee** [patricegautier/unifiZabbix#28]
Tried setting this up today, and I keep receiving an error on a bunch of the data points. I attached a picture below of what the error is. I have not a clue of where to start with this. 

![image](https://user-images.githubusercontent.com/97147515/152422296-db75e52b-e793-4a46-8ac4-976f2e147bcf.png)

**Comment by patricegautier** [comment]
What's the value in your {$UNIFI_SSH_PRIV_KEY_PATH} , {$UNIFI_PRIV_KEY} and {$UNIFI_PUB_KEY} macros?

Administration > General > Macros?

See the readme for values..

**Comment by BennyDaBee** [comment]
![Uploading 34372D12-9BF2-497E-B967-458DDBD7730B.jpeg…]()

**Comment by BennyDaBee** [comment]
see below

![373503EB-A442-405B-8C5F-D7C16046FD6F](https://user-images.githubusercontent.com/97147515/152453500-a99e5aa4-d329-442c-a92a-e060c428af70.jpeg)

**Comment by patricegautier** [comment]
looks reasonable.. it does look to me there is a macro value missing somewhere.

anything interesting in the zabbix logs, usually at /var/log/zabbix, unless you are in a container

**Comment by BennyDaBee** [comment]
Just filled with these.

`1. Failed: cannot extract value from json by path "$.radio_table[?(@.athstats.cu_total >0)]": cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'Could not create directory '/var/lib/zabbix//.ssh'.
{"anon_id":"ff41d157-c8af-4fa9-8c8f-d84720f57fec","antenna_table":[{"default":true,"id":4,"name":"
  1289:20220203:200048.779 item "UniFi nanoHD:memory" became not supported: Cannot evaluate function: not enough data at "last(//mem_used) / last(//mem_total)".
  1289:20220203:200048.779 item "UniFi nanoHD:cpu" became not supported: Preprocessing failed for: Could not create directory '/var/lib/zabbix//.ssh'...{"anon_id":"ff41d157-c8af-4fa9-8c8f-d84720f5...`

**Comment by BennyDaBee** [comment]
Fixed this just by creating the missing directory in /var/lib. As soon as I did that all errors cleared.

**Comment by patricegautier** [comment]
Great!
