### ISSUE TITLE
WiFi channel number discovery

### ISSUE THREAD

**Issue by luponata** [patricegautier/unifiZabbix#29]
Hello, in the json output of mca-dump I found the informations on the numbers of channels of the transmitted WIFI networks:

```
"ccq":991, "channel":1, "dns_avg_latency":-1, "essid":"WIFIA"

"ccq":333, "channel":108, "dns_avg_latency":10, "essid":"WIFIB"
```

Would it be possible to add them to the template?

It would be more convenient than looking through the Unifi Controller events: (the AP changed the channel from "6" to "1")

:)

**Comment by patricegautier** [comment]
Straightforward enough.  Try that last commit..

The channel detection works fine.  I added a trigger to fire on channel change but haven't tested it.

**Comment by patricegautier** [comment]
closing this one..
