### ISSUE TITLE
No Such Object available on this agent at this OID

### ISSUE THREAD

**Issue by lslamp** [patricegautier/unifiZabbix#3]
Greetings,

I am not sure if it is something that I have done wrong or my lack of understanding of the SNMP setup and process, not no matter I do I cannot get many of the graphs to deliver data.
If I look at the items under a host, I see a lot of items with the status Not Supported is shown in attachment (Status_Not_Supported.png). If I then try to run a text of the item itself, I get the error shown in the attachment. (CPU_Average_Load.png) and (CPU_Average_Load_No_Object.png).

I also had the issue of failing the import for temperature.cpu. I removed the elements from the xml file and then it imported successfully.,  Then I also did not understand why an ssh key needed to be shared to probe devices for data.

I don't understand why the OIDs seem to be missing from many of my devices.
Attached is a missing objects list for 3 tests, 1, cpu load, 2. incoming traffic and 3. outgoing traffic.
[Missing_Object.txt](https://github.com/patricegautier/unifiZabbix/files/5542125/Missing_Object.txt)

Thanks
Lawrence

**Comment by patricegautier** [comment]
Hi @lslamp I am afraid you lost me.. The templates in this project do not use SNMP in any way so running snmpwalk is exposing different and completely unrelated issues I think.
