### ISSUE TITLE
UDM Fan speed

### ISSUE THREAD

**Issue by pax0707** [patricegautier/unifiZabbix#32]
Would it be possible to add support for fan speed?

From what I can see it's only for switch.

**Comment by patricegautier** [comment]
mm.. I can't seem to find a way to get that value;  as far as I can tell it's not included in mac-dump, and ubnt-fan-speed just hangs in my tests..

**Comment by pax0707** [comment]
Yeah, it's not in the dump file...

**Comment by patricegautier** [comment]
Well not sure how to solve that one - if you find a way to get the udm fan speed from the cmd line, connecting to the template is easy..

**Comment by pax0707** [comment]
Id displays with sensors command.
Not sure how to incorporate that.

```
# sensors
lm63-i2c-0-4c
Adapter: Synopsys DesignWare I2C adapter
fan1:        2351 RPM  (min = 1748 RPM)
temp1:        +73.0 C  (high = +70.0 C)                  ALARM (HIGH)
temp2:        +85.1 C  (low  =  +0.0 C, high = +94.0 C)
                       (crit = +93.0 C, hyst = +83.0 C)
```

**Comment by patricegautier** [comment]
Ok works here too - easy to add.

This is what I get on a UDM pro:

adt7475-i2c-4-2e
Adapter: i2c-0-mux (chan_id 3)
in1:          +0.89 V  (min =  +0.00 V, max =  +2.99 V)
+3.3V:        +3.22 V  (min =  +0.00 V, max =  +4.39 V)
fan1:         722 RPM  (min =    0 RPM)
fan2:           0 RPM  (min =    0 RPM)
fan3:           0 RPM  (min =    0 RPM)
fan4:           0 RPM  (min =    0 RPM)
temp1:        +42.2 C  (low  = -63.0 C, high = +191.0 C)
                       (crit = +100.0 C, hyst = +96.0 C)
Board Temp:   +40.8 C  (low  = -63.0 C, high = +191.0 C)
                       (crit = +100.0 C, hyst = +96.0 C)
temp3:        +40.0 C  (low  = -63.0 C, high = +191.0 C)
                       (crit = +100.0 C, hyst = +96.0 C)

What kind of UDM were you testing against?

**Comment by pax0707** [comment]
The base one, nonpro.

**Comment by patricegautier** [comment]
Hi there - checkout today's commit.. it integrates fan speeds for UDMPs.   Caveat though there are a lot of other changes I had been working on, preparing for a new major releases.

**Comment by patricegautier** [comment]
closing this one.  please reopen after trying the latest commits..

**Comment by pax0707** [comment]
Sorry, I missed the notification for this issue.

Working as intended now.
Both temperatures and fan speed are showing, agreeing with sensors output.
Cheers,
