### ISSUE TITLE
missing zbx_export_templates.xml

### ISSUE THREAD

**Issue by MrSchmaltz** [patricegautier/unifiZabbix#35]
You mention to Import zbx_export_templates.xml, where can I find it?

**Comment by mtheofy** [comment]
It's in the repository.
Direct [link](https://github.com/patricegautier/unifiZabbix/blob/b672478493b34eba909d958b39ccba5ec31ef99f/zbx_export_templates.yaml)

**Comment by MrSchmaltz** [comment]
@mtheofy thank you for your reply, the file in the repository is a YML and Zabbix is looking for XML file, I trayed rename it to xml but the Zabbix still don't like it.

**Comment by mtheofy** [comment]
Did you try to import it as a YML? 
It was not an issue for me

**Comment by MrSchmaltz** [comment]
this Is the error message from Zabbix when I tried import yml file: Import failed
Cannot read XML: (4) Start tag expected, '<' not found [Line: 1 | Column: 1].

**Comment by mtheofy** [comment]
@MrSchmaltz : Which version of zabbix are you using?

**Comment by mkevenaar** [comment]
> this Is the error message from Zabbix when I tried import yml file: Import failed Cannot read XML: (4) Start tag expected, '<' not found [Line: 1 | Column: 1].

Make sure the file is named correctly and you have a version of Zabbix that supports yaml

**Comment by MrSchmaltz** [comment]
zabbix_server (Zabbix) 5.0.20

**Comment by MrSchmaltz** [comment]
Does you guys have any template compatible to Version 5?

**Comment by mtheofy** [comment]
@MrSchmaltz  yml files are supported from zabbix version 5.2 onwards
[https://www.zabbix.com/whats_new_5_2](https://www.zabbix.com/whats_new_5_2)
