### ISSUE TITLE
Unknown device Type: USG

### ISSUE THREAD

**Issue by LiamColeUM** [patricegautier/unifiZabbix#36]
Hope I'm just being stupid. 

When I run the mca dump from Zabbix I get "Unknown device Type: USG". However when I run the command directly from the terminal all seems to work fine. 

I'm using the following for the MCA Dump key " mca-dump-short.sh[ "-d", "{HOST.CONN}", "-p", "/home/administrator/Documents/key.txt ","-u", "{$UNIFI_USER}", "-t", "USG"] "

Cheers, 

Liam

**Comment by patricegautier** [comment]
in key.txt is it a private key or a password?

either way shouldn't cause the unknown type problem though..

**Comment by patricegautier** [comment]
Reading the code I don't see how you can get this unknown type problem.. Is there a hidden character in the key definition?

**Comment by LiamColeUM** [comment]
the key.txt is a password file. I've tried every variation I can think of in the key within Zabbix as this seems to be where the error is being thrown from.

**Comment by patricegautier** [comment]
Trying to clean up.. Is this still an issue?

**Comment by LiamColeUM** [comment]
All good now, thanks :)

**Comment by patricegautier** [comment]
ok!
