### ISSUE TITLE
Data Drop

### ISSUE THREAD

**Issue by M0okz** [patricegautier/unifiZabbix#38]
Hello,

Me again :) !
Today i have a little problem with one of my gateway, sometimes datas not show up, in logs of zabbix server i found this (disconnecting and reconnecting)
![image](https://user-images.githubusercontent.com/87419947/166430743-0e16d068-5eeb-41ec-8703-7dff320ec020.png)
On graph it look like : 
![image](https://user-images.githubusercontent.com/87419947/166430848-bdb88e61-8758-4479-8ffa-d54328aa6fca.png)
Regards ! Thx

**Comment by patricegautier** [comment]
Trying to clean up.. Is this still an issue?

**Comment by patricegautier** [comment]
closing in absence of feedback
