### ISSUE TITLE
Device not reporting statistics

### ISSUE THREAD

**Issue by JAARS-RW** [patricegautier/unifiZabbix#39]
We are slowly working on replacing our network gear with all Unifi equipment. Recently, as I've been installing more switches, I've seen quite a few of our devices stop reporting statistics with these templates. I tried increasing the StartPrepocessors value in the Zabbix config. That seemed to get a couple back, but only a handful so I don't think that's really the problem. Any idea why these would stop reporting?

**Comment by patricegautier** [comment]
2 things to look at:
 - in the UI go the device not reporting stats, look at its items and look for unsupported items, in particular mca-dump.  the error message there if any should be a good clue
 - also look in the zabbix server logs

**Comment by JAARS-RW** [comment]
These are the items that show as unsupported. All but one of the errors say "Timeout while executing a shell script." The one that's different reads "Cannot evaluate function: not enough data at "avg(//cpu,{$UNIFI_SMOOTHING_PERIOD})" on the cpu_smooth item.
![image](https://user-images.githubusercontent.com/97243431/168609703-b522af38-49a3-4ced-8631-8ed02c0afa8b.png)
Haven't had a chance to check logs yet.

**Comment by JAARS-RW** [comment]
I think I found the issue. I was missing the {$UNIFI_CHECK_TIMEOUT} macro. I upped the timeout in the Zabbix server config and added that macro and I haven't seen any more "Device not reporting statistics" messages.

**Comment by patricegautier** [comment]
Thanks - I wish there was a way for Zabbix to explicitly flag those unset macros..

**Comment by JAARS-RW** [comment]
Thank you for you help!
