### ISSUE TITLE
Unifi firmware v6 on switch, broke template: {"mcaDumpError":"Error", "reason":"timeout" }

### ISSUE THREAD

**Issue by luponata** [patricegautier/unifiZabbix#41]
Zabbix version: 5.4.3 (with original template installed a year ago)
Switch model: US-16-150W
Switch version prior issue: 5.76.7
Switch version with issue: 6.2.14.13855

Everything was working the minute before the firmware upgrade (the problem arised only with the switch, the 2 APs was upgraded a month ago without problems)

----------
By manually testing "mca-dump" on zabbix i got:

`{"mcaDumpError":"Error", "reason":"timeout" }`

Checking all relatives items gives: 
```
Preprocessing failed for: {"mcaDumpError":"Error", "reason":"timeout" }
1. Failed: cannot extract value from json by path "$.model_display": no data matches the specified path
```

**Comment by patricegautier** [comment]
There are 2 timeouts you might want to try to set to see if that helps:
- the Zabbix timeout itself:  (ZBX_TIMEOUT in the zabbix server conf) - try maybe something 5-10s
- if you are up to date on the template, there is a timeout for mac-dump that you can set with the {$UNIFI_CHECK_TIMEOUT} macro.  Same thing 5-10s..

**Comment by luponata** [comment]
Hi,

My version of the template didn't had the "{$UNIFI_CHECK_TIMEOUT}" macro inside the mca-dump items, after updating them, everything works correctly

The last firmware major version, likely increased the SSH login time (doubled by checking manually)
