### ISSUE TITLE
Get error on test conection

### ISSUE THREAD

**Issue by cclcyber** [patricegautier/unifiZabbix#43]
Hi there, i´m following your instructions on zabbix server and when i try to test the conection with command line:

 sudo -u zabbix /usr/lib/zabbix/externalscripts/mca-dump-short.sh -d <theDeviceIP> -u <yourUnifiUserName> -i <fullPathToYourPrivateKey> -t <UDMP|AP|SWITCH|CK>

I get the error:

**bash: sintax error near token unexpected `newline'**

And not run.

Can you help me? 

Thx.

**Comment by luponata** [comment]
You must enclose command in quotes:

sudo -u zabbix **"**/usr/lib/zabbix/externalscripts/mca-dump-short.sh -d -u -i -t <UDMP|AP|SWITCH|CK>**"**

**Comment by patricegautier** [comment]
also you need to pick the appropriate type for the -t flag for the device you are trying to reach, and put username@device at the end..

**Comment by patricegautier** [comment]
closing in absence of activity
