### ISSUE TITLE
Error with uname in both SSH templates

### ISSUE THREAD

**Issue by pax0707** [patricegautier/unifiZabbix#44]
Getting "Two items ("uname" and "uname") cannot populate one host inventory field "OS (Full details)", this would lead to a conflict." while trying to import template to hosts.

**Comment by patricegautier** [comment]
Which templates is the host getting the error linked to?

**Comment by pax0707** [comment]
I have only one of them assigned per host.
Couldn't add them unless I delete uname item.
I didn't try to add both Unifi SSH High Priority Host and Unifi SSH Host for the same host.

![image](https://user-images.githubusercontent.com/3536230/171757880-4840f964-611d-4085-a286-4c3917eef4c3.png)

**Comment by patricegautier** [comment]
Ok - then exactly when/where are you getting the error?

**Comment by pax0707** [comment]
Host:
1 add Unifi UDMP
2 add Unifi SSH High Priority Host
3 update - error

Same when trying to add Unifi AP + Unifi SSH Host to another host.

**Comment by patricegautier** [comment]
What does 'update' mean exactly?  Re-import the templates?

**Comment by pax0707** [comment]
When I press update, after adding templates to a host.
![image](https://user-images.githubusercontent.com/3536230/171759968-55dc0f35-aa80-4e42-93e6-4ed7a3529569.png)

**Comment by pax0707** [comment]
I was also getting the error when importing a new version of the template into Zabbix but I fixed that by deleting the templates from zabbix and reimporting clean.

**Comment by patricegautier** [comment]
I am removing the inventory assignment from the templates - it causes more problems than it solves..

**Comment by patricegautier** [comment]
Let me know if it solves this issue..

**Comment by patricegautier** [comment]
did you get a try to chance the update?

**Comment by pax0707** [comment]
Sorry, no.

Vacation time. 
I'll be back home next week and try.
