### ISSUE TITLE
Cannot access public key file....

### ISSUE THREAD

**Issue by joshrathke** [patricegautier/unifiZabbix#49]
From what I can tell I have followed the instructions according to the documentation but am running up against this error:
`<AP_NAME>:ssh.run[uname]" changed: Cannot access public key file /home/ec2-user/.ssh/zabbix/zb_id_rsa.pub`

Additionally I get another error relating to the Private Key which I am assuming is the same access type error but it is harder to read because it is buried in a longer error log and eventually gets truncated: `Preprocessing failed for: {"mcaDumpError":"Error", "reason":"Warning: Identity file /home/ec2-user/.ssh/zabbix/zb_id_rsa no...`

When I do the test run as described in the documentation I get the JSON blob back just fine and no errors, so I'm not quite sure where to go from here. Copying and pasting the path found in the error dumps me in the folder where the keys can be found so the path and filenames seem to checkout.

Any ideas?

**Comment by UntestedEngineer** [comment]
Containerized environment or traditional monolithic?  Do you have user/ownership correctly for the zabbix user to rsa keys?  If If it is a containerized environment I have found you need to set proper mod permissions instead to the rsa keys.

**Comment by joshrathke** [comment]
Ah, that was it. It's an EC2 instance, so assuming that means it is containerized even though it is touted as essentially a VM infrastructure rather than a more traditional ECS cluster using many containers for a single service.

Either way I created a `/home/zabbix/.ssh` directory and copied the `zabbix` folder with the keys, followed by updating the SSHKeyLocation parameter in the conf and finally the key location macro at which point everything started working as expected. Thanks for your callout!
