### ISSUE TITLE
mca-dump: command not found

### ISSUE THREAD

**Issue by lD2003** [patricegautier/unifiZabbix#5]
This is probably a user issue, but I'm running into an issue when executing this command to test that I can pull data from the device.  The device i'm testing against is a CloudKey Gen2 Plus. 

When I run the command below with my parameters I get
sudo -u zabbix /usr/lib/zabbix/externalscripts/mca-dump-short.sh -d <theDeviceIP> -u <yourUnifiUserName> -i <fullPathToYourPrivateKey> -t <UDMP|AP|SWITCH|CK>

I get mca-dump: command not found  is that because im trying to pull data from the CK plus?

**Comment by patricegautier** [comment]
indeed the cloud keys do not support mca-dump..

have you tried pointing to your router (either USG or UDMP) and/or the APs?

**Comment by lD2003** [comment]
Yes, pulling data from the mesh AP's and Switch are working just fine.
Thanks for your help.

**Comment by patricegautier** [comment]
future expansion might be to pull data from the controller from the CKs or the UDMP and do discovery and stats from there..
