### ISSUE TITLE
Upgrade version

### ISSUE THREAD

**Issue by tocks53** [patricegautier/unifiZabbix#50]
Bonjour,

Je suis dans la version du 08_2021.

Je souhaiterais mettre à jours vers la nouvelle version.
Pourriez vous mettre un point update dans la doc.

Si je comprends bien, je dois copier ssh-run.sh et mca-dump-short.sh avec les bon droits.
Avant il n'y avait pas le ssh-run, mais seulement le mca-dump ?

Mais c'est plus pour la partie import des templates .

Comment devons nous procéder ?

Merci

**Comment by patricegautier** [comment]
bonne question.. I will add something

**Comment by patricegautier** [comment]
Added a section to the README..  lmk if I missed something.
