### ISSUE TITLE
Error:  Cannot evaluate function: not enough data at "avg(//cpu,{$UNIFI_SMOOTHING_PERIOD})".

### ISSUE THREAD

**Issue by Mighty33** [patricegautier/unifiZabbix#51]
Hi Getting a few errors...  as per the attached. Also attached the log files from server. 
Can anyone help a brother?

Cannot evaluate function: not enough data at "avg(//cpu,{$UNIFI_SMOOTHING_PERIOD})".
Cannot evaluate function: not enough data at "avg(//download_bandwidth,{$UNIFI_SMOOTHING_PERIOD})".
Timeout while executing a shell script.
Cannot establish SSH session: Timeout connecting to 192.168.20.1
Cannot evaluate function: not enough data at "last(//mem_used) / last(//mem_total)".
Public key try failed: Access denied for 'publickey'. Authentication that can continue: publickey,password

<img width="1000" alt="error" src="https://user-images.githubusercontent.com/35414147/175790936-b6a35666-bb7f-4629-abee-70c3df2142d9.png">

[Log Files.txt](https://github.com/patricegautier/unifiZabbix/files/8985604/Log.Files.txt)

**Comment by patricegautier** [comment]
Looks pretty clear the zabbix server can't get to 192.168.20.1 via ssh.

try to run:

/usr/lib/zabbix/externalscripts/mca-dump-short.sh -v -d '192.168.20.1' -u 'P1Admin' -i '/var/lib/zabbix/' -t 'USG'

from the command line..

**Comment by patricegautier** [comment]
closing in absence of activity..
