### ISSUE TITLE
With more recent ssh versions, such as Ubuntu 22, you must modify /etc/ssh/ssh_config on the zabbix host

### ISSUE THREAD

**Issue by Kelly12612** [patricegautier/unifiZabbix#54]
Just running through setting this up for the first time with Zabbix 6.2 on a new Ubuntu 22.04 VM, the ssh-rsa algorithms are turned off by default, to fix it so that ssh into the UDMP will work without a password, edit the file /etc/ssh/ssh_config and add the lines below under the "Host *" line:

> Host *
>    PubkeyAcceptedAlgorithms +ssh-rsa
>    HostkeyAlgorithms +ssh-rsa

Thanks for publishing this!

**Comment by patricegautier** [comment]
yep - I also added

-o PubkeyAcceptedKeyTypes=+ssh-rsa -o HostKeyAlgorithms=+ssh-rsa

to ssh invocations from the external scripts to make this a bit easier..
