### ISSUE TITLE
The README mentions Unifi Router but it wasn't in the imported list.

### ISSUE THREAD

**Issue by Kelly12612** [patricegautier/unifiZabbix#55]
After importing I see the following Unifi templates: AP, Protect Camera, Protect Cloud Key, Protect NVR4, SSH Host, Switch, USG, WiFi Site, SSH High Priority Host and UDMP, I don't see Router.

Also, can you please clarify for the UDMP, should we add the Unifi Switch template also, or just the UDMP and SSH High Priority Host?
Thanks.

**Comment by Kelly12612** [comment]
Hmm, actually I'm unable to add Switch to a UDMP because it depends on SSH Host, and I already have SSH High Priority Host selected for UDMP, so that question might be answered.

**Comment by patricegautier** [comment]
Finally catching up here..  You are correct, you can't add the switch template to a UDMP.   

The switch ports should be discovered from the UDMP template directly, so as far as I know everything is good there..
