### ISSUE TITLE
When running test command "mca-dump-short.sh" I receive gzip: stdin: unexpected end of file

### ISSUE THREAD

**Issue by jsmithis101** [patricegautier/unifiZabbix#57]
sudo -u zabbix /usr/lib/zabbix/externalscripts/mca-dump-short.sh -v -d '172.20.1.1' -u 'root' -p '/var/lib/zabbix/.ssh/password' -t 'UDMP'
ssh -o LogLevel=Error -o StrictHostKeyChecking=accept-new  root@172.20.1.1 "mca-dump | gzip" | gunzip | jq  del (.dpi_stats) | del(.fingerprints)

gzip: stdin: unexpected end of file

**Comment by patricegautier** [comment]
try without the gzip and the gunzip to see..  

sudo -u zabbix /usr/lib/zabbix/externalscripts/mca-dump-short.sh -v -d '172.20.1.1' -u 'root' -p '/var/lib/zabbix/.ssh/password' -t 'UDMP' ssh -o LogLevel=Error -o StrictHostKeyChecking=accept-new root@172.20.1.1 "mca-dump"  | jq del (.dpi_stats) | del(.fingerprints)

**Comment by patricegautier** [comment]
closing in absence of activity..
