### ISSUE TITLE
ssh-copy-id fails with error /usr/bin/ssh-copy-id: ERROR: mktemp failed

### ISSUE THREAD

**Issue by s0undy** [patricegautier/unifiZabbix#59]
When running "sudo -u zabbix ssh-copy-id -i <privatekey> myusername@ip-addr" the following error appears:

/usr/bin/ssh-copy-id: 59: cd: can't cd to /var/lib/zabbix/
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "zb_id_rsa.pub"
The authenticity of host 'ip-addr' can't be established.
RSA key fingerprint is <correct fingerprint>.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
mktemp: failed to create file via template ‘/var/lib/zabbix//.ssh/ssh-copy-id_id.XXXXXXXXXX’: No such file or directory
/usr/bin/ssh-copy-id: ERROR: mktemp failed

Tried creating new keys, different locations, checked premissions but so far no succes. 
Will try to find a solution and update.

Ubuntu 20.04
Zabbix 6.0.7

**Comment by s0undy** [comment]
More info:

Ubuntu 20.04 
Zabbix 6.0.7

**Comment by patricegautier** [comment]
ip-addr is the name of your actual host?

**Comment by patricegautier** [comment]
Trying to clean up.. Is this still an issue?

**Comment by patricegautier** [comment]
closing in absence of feedback
