### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by Intrudr-Sec** [patricegautier/unifiZabbix#6]
Salut Patrice

Dans la version 5.2, je ne vois pas cette option `Zabbix, in Administration > General > Macros, you will need to set a value for all the following macros`
Tout le reste fonctionne par contre. 
Je peux te montrer des logs au besoin.

Merci pour tout, pratique ce plugin ;)

**Comment by Intrudr-Sec** [comment]
ok, erreur du pitcher, une fois dans Administration/General, il faut cliquer sur "GUI" en haut de la page.
Un menu deroulent sera disponible avec l'option "Macros"

sur ce lache pas

**Comment by patricegautier** [comment]
Je reconnais c'est pas très intuitif..
