### ISSUE TITLE
Switch Port Discovery not working - Preprocessing failed for: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 112: /usr/bin/expect: No such file or dir...

### ISSUE THREAD

**Issue by Quice2605** [patricegautier/unifiZabbix#60]
Preprocessing failed for: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 112: /usr/bin/expect: No such file or dir...
1. Failed: cannot extract value from json by path "$.port_table": cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: '/usr/lib/zabbix/externalscripts/mca-dump-short.sh: line 112: /usr/bin/expect: No such file or directory
{"anon_id":"c0f56720-930c-4c70-8bb2-84aac8abfd5

What i need ?

**Comment by patricegautier** [comment]
which platform are you running the zabbix server on?

What's the result of running 

which expect

on the command line?

The 'expect' package needs to installed..

**Comment by tjarosz-stdair** [comment]
I noticed the same issue on Ubuntu 20.04. I was seeing the error about /usr/bin/expect was missing. The commands to install expect:

sudo apt-get update
sudo apt-get install expect

The above commands installed the package and now the folder /usr/bin/expect exists. Now to continue the troubleshooting.

**Comment by patricegautier** [comment]
so looks like this particular issue is closed..
