### ISSUE TITLE
Custom ssh port?

### ISSUE THREAD

**Issue by siegfried2u** [patricegautier/unifiZabbix#61]
Hi and thank you so much for your effort. We can monitor now what is going on in the wifi area.

The possibility to set a macro with a custom ssh port would really help us monitoring also the unifi APs from our other sites, which are of course behind NAT.

Thank you very much.

**Comment by patricegautier** [comment]
I'll take a look.. but have you thought about setting up a point to point VPN between your sites?

**Comment by siegfried2u** [comment]
We have site-to-site vpn in some locations and there is no problem. Other sites have only single public ip with ddns and some very low budget routers without serious vpn capabilities.
Thank you.

**Comment by patricegautier** [comment]
So you would expose every AP under the one public IP with a custom port?

**Comment by patricegautier** [comment]
Take a look - I added custom ssh port support for APs.

Just specify a UNIFI_SSH_PORT macro on each APs that needs a port !=22

Let me know..

**Comment by patricegautier** [comment]
closing this without activity
