### ISSUE TITLE
Ubuntu 20.04 libssh - fix with PPA does not work anymore

### ISSUE THREAD

**Issue by zpolisensky** [patricegautier/unifiZabbix#62]
Hi @patricegautier ,

this is just FYI that Ubuntu 20.04 libssh fix _'In Ubuntu 20.04 the "ssh.run" key does not work with the standard libssh. Just install the latest version from https://launchpad.net/~kedazo/+archive/ubuntu/libssh-0.7.x and everything is OK.'_ does not work anymore because libssh library in this repository was upgraded to 0.10.x and this version doesn't support weak encryption algorithms used by some Unifi devices (like APs).
Possible solution is to upgrade from Ubuntu 20.04 to 22.04 where is libssh-0.9.6 by default and that works fine.

Thanks
Zbynek

**Comment by patricegautier** [comment]
Hi Zbynek,

Thanks for the heads up,

Presumably RSA support for ssh can still be turned on by configuration with libssh 0.10.x, it’s just off by default right?

	-P

**Comment by zpolisensky** [comment]
Hi Patrice,
to be honest, I don't know if it has been removed completely or just disabled and can be re-enabled by some configuration. I just upgraded my server to Ubuntu 22.04 with libssh 0.9.6 to fix that issue.
Here is Zabbix error with libssh 0.10.3:
**Cannot establish SSH session: kex error : no match for method server host key algo: server [ssh-rsa,ssh-dss], client [rsa-sha2-512,rsa-sha2-256,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256]**

Thanks
Zbynek

**Comment by patricegautier** [comment]
BTW I will mention that for those items that use the external scripts, I added 

-o PubkeyAcceptedKeyTypes=+ssh-rsa -o HostKeyAlgorithms=+ssh-rsa

to SSH invocation to deal with this..  So only items that use ssh.run are affected as of now..
