### ISSUE TITLE
Timeout while executing a shell script... and other errors.

### ISSUE THREAD

**Issue by tjarosz-stdair** [patricegautier/unifiZabbix#63]
I have this Unifi monitoring solution installed and partially working. In my Zabbix "problems" page. All the Unifi devices I have setup are showing "[Unifi device name] has not reported statistics for more than 10m". When I look at the device under "Latest data" I see the Unifi device has some data present but the mca_dump items are showing errors. On the mca_dump, it shows the following:

![image](https://user-images.githubusercontent.com/62894936/192795489-013f7243-8ff5-4ab5-b9d1-3671e894285f.png)

`"Preprocessing failed for : {"mca:DumpError':'Error", "reason":"@@@@@@...",1. Failed: Cannot perform regular expression "mcaDumpError" validation for value of type "string" value matches regular expression`

On the other mca_dump_xxx items, it shows an error for "Timeout while executing a shell script". I also saw an error, can't remember exactly where, but it was showing a path missing on line 112 of mca-dump-short.sh. This is the same error as in issue #60. Following that issue, I installed the "expect" package for Ubuntu which hopefully resolves that error. You might want to add to the readme file a list of dependencies and include that expect package since it isn't part of the Ubuntu by default. 

When I test the mca-dump-short.sh script from the Ubuntu terminal, it runs successfully. Here's the command I used:
`sudo /usr/lib/zabbix/externalscripts/mca-dump-short.sh -v -d '192.168.80.28' -u '[UnifiSSHUsername]' -i  '~/.ssh/zabbix/zb_id_rsa' -t 'AP' -p ''`
I added the blank password because when examining the mca-dump item on the zabbix host, I saw that the -p was included in the command but since I don't have that macro defined it would be passed as a blank string. When I run the above command, I get a JSON dump of data from the Unifi device. That proves the script is working and the SSH keys are functioning for login. 

Any ideas on where to troubleshoot next?

**Comment by tjarosz-stdair** [comment]
Here's a little more information I found while poking around. If you go to zabbix Latest data page and filter to a single Unifi device. Click on the mca-dump item and select "configuration" from the menu, then click "Preprocessing" at the top of the item config page, then click "Test" next to the only preprocessing step. At the top of the testing page, click "Get value from host" then click the "Get value" button. Now the value is populated, click the value to display it. My value was an error message about the permissions on the private key file as seen here:

![image](https://user-images.githubusercontent.com/62894936/192814314-d10f6692-9edb-4841-a698-69fd7bf5b044.png)

I had to modify the permissions on the private file:  chmod 700 zb-id-rsa

After changing the permissions, it looks like it's pulling a good value in the mca-dump testing. In my zabbix latest data page, it's showing a lot more data and no errors on the mca-dump. It's still showing a timeout error next to the mca-dump-switch-discovery item. Looks like I'm almost 100%.

**Comment by patricegautier** [comment]
> I added the blank password because when examining the mca-dump item on the zabbix host, I saw that the -p was included in the command but since I don't have that macro defined it would be passed as a blank string

Actually that's not what happens - an empty macro doesn't get substituted at all and you get {$THE_NAME_OF_THE_MACRO} into the script and mca-dump-short deals with this correctly.  You should remove the -p option..

**Comment by patricegautier** [comment]
if you go to Configuration > Host, pick one of the hosts in question, go to its items and mouse over one of the unsupported items, you should maybe see more info..

**Comment by tjarosz-stdair** [comment]
After some time. it looks like all the errors in Zabbix have resolved themselves. 

Good monitoring tool. Thanks for publishing.
