### ISSUE TITLE
Typos in AP Channel Utilization triggers

### ISSUE THREAD

**Issue by GMichu** [patricegautier/unifiZabbix#65]
![firefox_nnCAGzBgUo](https://user-images.githubusercontent.com/67835103/196117000-c57f281c-34b1-494a-9120-22835b187c4e.png)

1. Operational data does not display correctly due to a missing parenthesis in the opdata expression
2. Same goes for dependency expression - problems with severity of info and average are displayed simultaneously
3. There is also a minor problem in the logic of the AVERAGE trigger operational data - it displays the INFO trigger threshhold

**Comment by GMichu** [comment]
Also operational data should generally show item value and not threshold

**Comment by GMichu** [comment]
#66

**Comment by patricegautier** [comment]
Hi GMichu,

Thanks much for reporting this - looks to me you are right on all counts.

I included your changes in the latest commit; there are however quite a few other changes in there
