### ISSUE TITLE
SSH Agent

### ISSUE THREAD

**Issue by pax0707** [patricegautier/unifiZabbix#68]
Think something went snafu.

I can't get items that use sshrun to work.
On the test I get this:
![image](https://user-images.githubusercontent.com/3536230/196822309-67bb3b67-4b6e-47ae-bc7a-1424cec6df68.png)
One / too many and shouldn't it use the private key?

I would guess that key path should be "/usr/lib/zabbix/externalscripts" but when I use that mcadump doesn't work. This way it works but sshrun doesn't.
![image](https://user-images.githubusercontent.com/3536230/196823448-c7ff6274-198c-4f25-a48f-9ee037fdf4e5.png)

![image](https://user-images.githubusercontent.com/3536230/196823565-f7d6007a-cfb4-4007-af30-429b1ef2e95b.png)

**Comment by patricegautier** [comment]
the keys are in the wrong location likely..

What do you have for SSHKeyLocation in your zabbix_server.conf?

see the readme at "4/ You then need to point Zabbix to those keys."

**Comment by pax0707** [comment]
The same thing.
Without the trailing slash.

![image](https://user-images.githubusercontent.com/3536230/197397535-417fad2b-b3e3-4cc6-9087-2ab3f53855d5.png)

**Comment by patricegautier** [comment]
mm.. when you say mac-dump doesn't work, what's the error?

**Comment by patricegautier** [comment]
Also, for what it's worth, I have the keys in a separate directory from the script directory.

ssh can be quite paranoid about permissions too, so maybe the ownership of the directory above the keys matters
