### ISSUE TITLE
Question about version support

### ISSUE THREAD

**Issue by greavette** [patricegautier/unifiZabbix#71]
Hello,

Thank you very much for making this template available for all to use.  

I have a question for you about support.  When it comes to a company or small business, I would much rather use a product that is supported for 5 years and not just 6 months.  This is why I choose to install and use the Zabbix LTS versions over the standard releases. 

So my question to you is..you mention that this template may not work on versions less than 6.2.  Can you tell me what issues or changes I may need to make to this UnifZabbix template to ensure it will work with Zabbix 6 LTS?

Thanks very much in advance for any advice you can provide me.

**Comment by patricegautier** [comment]
A reasonable thought.. but unfortunately I don't have enough of a setup and resources to test on both LTS and current, and I made the choice to stay on current for my use cases.  

At this point I am not aware of anything that would break going with LTS, but I can not guarantee that there isn't something.  I am happy to help solve issues that arise if you want to give that path a go..
