### ISSUE TITLE
SERVER_DISCOVERY returns nothing

### ISSUE THREAD

**Issue by RainCaster** [patricegautier/unifiZabbix#72]
This happens for me when clicking through the zabbix UI, and it also occurs when I run the mca-dump-short.sh script. 
-t SWITCH /  AP / UCK / UNVR4  works
-y SWITCH_FEATURE_DISCOVERY works too
-t SWITCH_DISCOVERY returns nothing

zabbix is running on Ubuntu LTS 22.04 with consistent updates.
My unifi network is managed by a UCKG2+ running 3.0.13 and Unifi Network is v7.3.76
The UNVR4 is running 3.0.13  with Protect  v2.6.17

I have 5 switches all are running the latest FW. 
   USW 16 Poe
   US 8 60W
   USW Flex Mini (these don't show up- which is normal)

**Comment by patricegautier** [comment]
try to run mca-dump-short with -vw see if anything pops out..

Also, anything interesting in the zabbix server logs?

**Comment by RainCaster** [comment]
Server logs show a number of different entries about timeouts. All t5he ones for SWITCH_DISCOVERY and SWITCH_FEATURE_DISCOVERY simply say "Timeout while executing a shell script." The SWITCH entries occasionally will show "became not supported: Timeout while executing a shell script." or "became supported".

**Comment by RainCaster** [comment]
Running the script manually with -vw shows:
ssh  -o PubkeyAcceptedKeyTypes=+ssh-rsa -o HostKeyAlgorithms=+ssh-rsa -o LogLevel=Error -o StrictHostKeyChecking=accept-new  tomf@192.168.0.253 mca-dump | jq  del (.port_table[].mac_table)
Port replacement Program: /tmp/unifiSwitchDiscovery/switchPorts-192.168.0.253.jq
jqProgramFile: /tmp/unifiSwitchDiscovery/switchPorts-192.168.0.253.jq

Of course, the .jq files are erased by the script if they ever existed.

**Comment by patricegautier** [comment]
The fan and temperature failures are expected, depending on the switch model.  They don’t all report those values.

For timeout issues, can you try to raise the zabbix timeout to say 10s (Timeout=10 in /etc/zabbix_server.conf)

Also try:
time ssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -o HostKeyAlgorithms=+ssh-rsa -o LogLevel=Error -o StrictHostKeyChecking=accept-new  ***@***.*** ***@***.***> 

And see how long that takes

	-P

**Comment by patricegautier** [comment]
> The script was taking about 3.7 to 4.8 sec to run. I changed the timeout to 10 in hopes of fixing the problems.
> 
Let me know if it does or not



> My version of Ubuntu did not have the "expect" package installed by default. The fix is "sudo apt install expect”
Updated the doc, thanks


> The latest version (11-20-22 commit) of the mca-dump-short.sh file sends out a large amount of debug junk. It looks like there is a big problem with the script.
-vw was way too verbose.  Try the latest commit, with just -v


	-P
