### ISSUE TITLE
Macros not imported?

### ISSUE THREAD

**Issue by hellojoe88** [patricegautier/unifiZabbix#77]
Hi,

for some reason I had to create these macro options although as I understood they should already come with the template:
![grafik](https://user-images.githubusercontent.com/1126804/211624625-c9e28b8f-a8d2-4ec3-8493-def5afffa65e.png)
Or did I misunderstand and have to create these macros by hand? They will be removed if I update the template from this github repo.

**Comment by patricegautier** [comment]
The macros do not come with the template; you have to create them by hand and adjust the values if desired.  They will survive subsequent imports..

**Comment by hellojoe88** [comment]
Thanks. I tried creating them in the imported templates but subsequent imports will delete the macros on update. I created a template of my own so they are inherited, so that is fixing my issue without a problem.

**Comment by patricegautier** [comment]
Ah - that’s the problem

Most if not all the macros should be created at the top level in Administration > General > Macros and those will survive.

It is true that Macros directly on the template will get overridden and your solution is great for that.  I will add that to the doc..

	-P
