### ISSUE TITLE
zabbix template import failure

### ISSUE THREAD

**Issue by SkorpionMB** [patricegautier/unifiZabbix#78]
![Screenshot (2)](https://user-images.githubusercontent.com/122398926/211645593-26d439ae-d341-46c1-9602-50465d8a1eed.png)

running zabbix v6.2 on debian 11in a Proxmox container with proxmox VE v7.3-4

in your documentation is a zbx_export_template.xml for importing in zabbix
on your github Site is only a zbx_export_template.yaml
i tried the .yaml but get the error as in the screenshot
what can i do ?
thank you

**Comment by patricegautier** [comment]
.yaml is the correct file to import.  I will fix the remaining references to .xml in the doc.

Are you sure you are importing the correct file though?  the <doctype HTML> looks like the start of an HTML file..
