### ISSUE TITLE
Error importing template

### ISSUE THREAD

**Issue by daven1985** [patricegautier/unifiZabbix#8]
Good Afternoon,

When importing the template I get the below error... any thoughts?

Cannot read XML: (41) Specification mandates value for attribute data-pjax-transient [Line: 68 | Column: 90].

**Comment by daven1985** [comment]
Sorry ignore this. I hadn’t saved the file 100% correctly. Fixed by grabbing the file from the raw text instead of copying within the browser.

**Comment by patricegautier** [comment]
Closing then..
