### ISSUE TITLE
.sh connect issues?

### ISSUE THREAD

**Issue by Rattleheadie** [patricegautier/unifiZabbix#85]
Hi Patrice
Looking for some help. Im having 2 main issues by the looks of it. 
1. Related to the UDMP
2. Issue with both my switch and APs  noit pulling data except for ping. 

**_Issue 1._**
When I try to install the .pub file onto my UDMP I get the following error
Command Im using is
`>sudo -u zabbix ssh-copy-id -i zb_id_rsa.pub root@xx.xx.xx.xx`

```
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "zb_id_rsa.pub"
mktemp: failed to create directory via template ‘/var/lib/zabbix//.ssh/ssh-copy-id.XXXXXXXXXX’: No such file or directory
/usr/bin/ssh-copy-id: ERROR: failed to create required temporary directory under ~/.ssh
```

I have also tried using the full path where the .pub file is located with no success.

`>sudo -u zabbix ssh-copy-id -i /home/rattlehead/.ssh/zabbix/zb_id_rsa.pub root@xx.xx.xx.xx`
`/usr/bin/ssh-copy-id: ERROR: failed to open ID file '/home/rattlehead/.ssh/zabbix/zb_id_rsa.pub': Permission denied`

**_Issue 2_** 
I believe I got thsi sorted, it was the permissions of the script. I dont know why it wasnt functioning. Got sorted though.

**Comment by patricegautier** [comment]
have you tried the updatePublicKey.sh script in the package, something like:

updatePublicKey.sh -I zb_id_rsa.pub -u zabbix root@xx.xx.xx.xx

Might result in the same problem..
