### ISSUE TITLE
Added Hosts not showing as 'Available'

### ISSUE THREAD

**Issue by brigzzy** [patricegautier/unifiZabbix#9]
Hello there!  I apologize if this is a super silly question, I'm still learning Zabbix, and I'm not super proficient with it yet.  I've set up the scripts and added a few hosts, and they're collecting data, but the hosts don't appear as 'available' on the dashboards:

![image](https://user-images.githubusercontent.com/6279621/103467158-0dfe2e80-4d01-11eb-9eaf-73b04e0895d5.png)

Is that the expected behaviour, or have I configured something incorrectly?  Here is the host configuration:

![image](https://user-images.githubusercontent.com/6279621/103467172-2e2ded80-4d01-11eb-800c-92bb8c45048a.png)

Thanks so much for writing this template, it's awesome!

**Comment by patricegautier** [comment]
Try setting up a 'agent' interface instead of SNMP..

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/38435239/103505248-a504dc80-4e0e-11eb-9b6e-3808ab19b8c5.png">

**Comment by patricegautier** [comment]
I guess I'll close that one in the absence of more feedback..

**Comment by brigzzy** [comment]
I'm so sorry, I thought I had replied to this!  Yes, that fixed it.  Thank you so much for the quick reply!

**Comment by patricegautier** [comment]
No worries!
