### ISSUE TITLE
mca script issues

### ISSUE THREAD

**Issue by RemcoVroman** [patricegautier/unifiZabbix#91]
Hi,
I'm running Zabbix 6.2.7 and have a Unifi setup with a USG-Pro-4, uSW-Lite-16-POE and three UAP6MP.

On all of them I have issue's with the mca-dump-short.sh script: 

388969:20230215:100652.522 error reason for "FN-SW007:mca-dump-short.sh["-d","{HOST.CONN}", "-u", "{$UNIFI_USER}", "-i", "{$UNIFI_SSH_PRIV_KEY_PATH}", "-t", "SWITCH", "-p", "{$UNIFI_SSHPASS_PASSWORD_PATH}", "-U", "{$UNIFI_VERBOSE_SSH}", "-o", "{$UNIFI_CHECK_TIMEOUT}","-b"]" changed: Preprocessing failed for: { "at":"10:06:52", "r":"Remote pb: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ...
1. Failed: Error
388967:20230215:100656.526 error reason for "FN-AP0013:mca-dump-short.sh["-d","{HOST.CONN}", "-P", "{$UNIFI_SSH_PORT}", "-u", "{$UNIFI_USER}", "-i", "{$UNIFI_SSH_PRIV_KEY_PATH}", "-t", "AP", "-p", "{$UNIFI_SSHPASS_PASSWORD_PATH}", "-o", "{$UNIFI_CHECK_TIMEOUT}","-b"]" changed: Preprocessing failed for: { "at":"10:06:56", "r":"Remote pb: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ...
1. Failed: Error
388967:20230215:100724.542 error reason for "FN-AP0014:mca-dump-short.sh["-d","{HOST.CONN}", "-P", "{$UNIFI_SSH_PORT}", "-u", "{$UNIFI_USER}", "-i", "{$UNIFI_SSH_PRIV_KEY_PATH}", "-t", "AP", "-p", "{$UNIFI_SSHPASS_PASSWORD_PATH}", "-o", "{$UNIFI_CHECK_TIMEOUT}","-b"]" changed: Preprocessing failed for: { "at":"10:07:23", "r":"Remote pb: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ...
1. Failed: Error
388969:20230215:100730.544 error reason for "FN-AP0012:mca-dump-short.sh["-d","{HOST.CONN}", "-P", "{$UNIFI_SSH_PORT}", "-u", "{$UNIFI_USER}", "-i", "{$UNIFI_SSH_PRIV_KEY_PATH}", "-t", "AP", "-p", "{$UNIFI_SSHPASS_PASSWORD_PATH}", "-o", "{$UNIFI_CHECK_TIMEOUT}","-b"]" changed: Preprocessing failed for: { "at":"10:07:29", "r":"Remote pb: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ...
1. Failed: Error

The ssh login with the key's is working on all of them.

I suspect the banner displayed after the ssh login is conflicting with the script. I have not found yet how to remove the login banners. 

Is there a way to see what problem the mca script encounters ?

Best regards,
Remco

**Comment by RemcoVroman** [comment]
An additional screenshot from Zabbix at the latest data screen
![Zabbix-error-message_latest-data](https://user-images.githubusercontent.com/90851418/218986655-177b6754-adb4-480c-a048-eed49f63ea1b.jpg)

**Comment by RemcoVroman** [comment]
It seems my path to my private key was not correct. After fixing that, everything works fine.

**Comment by patricegautier** [comment]
Love those issues that close themselves..
