### ISSUE TITLE
mca-dump-short script timeout on UDM-SE

### ISSUE THREAD

**Issue by Just-Insane** [patricegautier/unifiZabbix#93]
When attempting to run the mca-dump-short script after configuring SSH keys, I keep getting a timeout error. I have tried both the script from the Main branch and the last tagged release. The exact error message is:

`{ "mcaDumpError":"Error", "reason":"time out with exit code 137", "device":"10.0.1.1" }`

I'm not sure if it's having an issue parsing any differences between an UDMP and UDM-SE, but I don't think there are that many?

Also, I tried setting the timeout flag to 30 seconds, with the same result. The script times out.

**Comment by Just-Insane** [comment]
I've also tried updating the timeout options mentioned in the README. The error log in zabbix_server.log is:

` Failed to execute command "/usr/lib/zabbix/externalscripts/mca-dump-short.sh '-d' '10.0.1.1' '-u' 'root' '-i' '/var/lib/zabbix/.ssh/zabbix/zb_id_rsa' '-t' 'UDMP' '-p' '{$UNIFI_SSHPASS_PASSWORD_PATH}' '-o' '15' '-b'": Timeout
while executing a shell script.`

I've also tried setting {$UNIFI_SSHPASS_PASSWORD_PATH} to `null` in the Zabbix UI, and that did not help. (Not sure if that's needed)

**Comment by patricegautier** [comment]
have you tried running that command by hand without the final -b from the zabbix server?

**Comment by Just-Insane** [comment]
Yes, I’ve tried the manual command on the server and it does not provide any more information even with the verbose flag set.

I have a UniFi Switch that I configured and it worked instantly once I updated the SSH settings in the UniFi app.

I know the UDM-SE doesn’t use the same ssh settings as the UniFi app, but I did confirm that SSH via keys works from the Zabbix server appliance as the zabbix user.

**Comment by Just-Insane** [comment]
Hmm. Looks like disabling SSH on the UDM, re-enabling and setting a new password, then rebooting has resolved the issue.

I rebooted due to noticing the UDM stuck in "Getting Ready", so I suspect it'd been an issue since the initial configuration.
