### ISSUE TITLE
Support for Zabbix 6.4.0

### ISSUE THREAD

**Issue by UntestedEngineer** [patricegautier/unifiZabbix#95]
I do not see a "Discussion" section so this was the only place I could put this.  Since Zabbix 6.4.0 went GA two days ago I have been testing with the 1.3 version of the UnifiZabbix application.  It seems to work as intended as in 6.2.X.  I will report any issues here that come up.

**Comment by patricegautier** [comment]
For what it's worth, I am running with 6.4 and no issues to report.

**Comment by patricegautier** [comment]
and I would be happy to set a version number from 6.4.0 onto the template set if anyone knows how to do that

**Comment by pax0707** [comment]
Came here to check on this exact thing.

Guess I can upgrade to 6.4 now.
;- ) =

**Comment by patricegautier** [comment]
6.4.2 even..
